Dockerfile.dapper
=> bump to go-1.6.2

Dockerfile.dapper, replica/diff_disk.go, replica/replica.go, trash.yml, vendor/github.com/rancher/sparse-tools/.gitignore, vendor/github.com/rancher/sparse-tools/LICENSE, vendor/github.com/rancher/sparse-tools/README.md, vendor/github.com/rancher/sparse-tools/directfio/directfio.go, vendor/github.com/rancher/sparse-tools/directfio/directfio_test.go
based on https://github.com/rancher/sparse-tools/pull/13
=> replica: switched to O_DIRECT

controller/control.go, frontend/tcmu/cfunc.go
=> Fix #51 Gracefully shutdown TCMU

frontend/tcmu/cfunc.go, frontend/tcmu/frontend.go, frontend/tcmu/main.go
This PR contains the TCMU issue in revert PR #110 , as well as another code cleanup for TCMU.
It can be merged separated.
=> Various TCMU fixes

app/replica.go, backend/remote/remote.go, replica/rest/router.go, rpc/client.go, rpc/types.go
- implemented "per request" read/write timeout
- replica ping is disabled
=> controller: read/write timeout

app/replica.go, backend/remote/remote.go, replica/rest/router.go
This reverts commit 42d2ee57f057d678b6f02e7b5a4239455d449f38.
=> Revert "controller: removed replica ping logic"

backend/remote/remote.go
- pingRetries = 6
- retry on any ping error
=> ping-retry

Dockerfile.dapper, app/controller_rest.go, frontend/rest/frontend.go, frontend/rest/model.go, frontend/rest/router.go, frontend/rest/server.go, integration/data/cmd.py, integration/data/common.py, integration/data/test_backup.py, integration/data/test_basic_ops.py, integration/data/test_snapshot.py, integration/setup.py, integration/tox.ini, scripts/integration-test
To provide another way to read/write data, so we can validate it through the
integration tests
Now it has snapshot revert/rm/backup create/restore test cases etc.
=> Add rest frontend and bunch of end-to-end data test cases

app/stats.go, controller/client/controller_client.go, controller/replicator.go, controller/rest/model.go, controller/rest/router.go, controller/rest/stats.go, main.go, rpc/client.go, rpc/types.go, trash.yml, vendor/github.com/rancher/sparse-tools/log/log.go, vendor/github.com/rancher/sparse-tools/stats/stats.go
isolated FDR from other changes
=> FDR: Controller R/W instrumentation

backup/backing_disable.go, backup/backing_qcow.go, backup/main.go, integration/data/test_backup.py, replica/backup.go, replica/backup_test.go, replica/replica.go, replica/replica_test.go
=> Fix backup with backing file

app/stats.go, backend/remote/remote.go, controller/client/controller_client.go, controller/rest/model.go, controller/rest/router.go, controller/rest/stats.go, main.go, rpc/client.go, rpc/types.go
- incorporated Darren's feedback: journal
- and missing commit from the yesterdays merge
=> Controller: minor tweaks 

integration/core/test_cli.py, integration/core/test_replica.py, integration/data/test_snapshot.py, replica/backup.go, replica/client/client.go, replica/replica.go, replica/replica_test.go, replica/rest/model.go, replica/rest/replica.go, replica/rest/router.go, replica/server.go, sync/agent/process.go, sync/sync.go, trash.yml, vendor/github.com/deckarep/golang-set/.gitignore, vendor/github.com/deckarep/golang-set/.travis.yml, vendor/github.com/deckarep/golang-set/LICENSE, vendor/github.com/deckarep/golang-set/README.md, vendor/github.com/deckarep/golang-set/set.go, vendor/github.com/deckarep/golang-set/threadsafe.go, vendor/github.com/deckarep/golang-set/threadunsafe.go
See https://github.com/rancher/longhorn/wiki/Snapshot-design for design.
Ready for merge
=> Coalescing fix using snapshot tree

agent/controller/controller.go
I noticed that if we do the add replica before the sync agent is up, it results in unnecessary adds and removes of replicas to the controller which was also generating lots of snapshot on the good replica
=> Ensure sync-agent up before adding replica

agent/controller/rest/backup.go
Add logic to to see if a particular backup or restore is in progress and if it is, just return the status.
Addresses https://github.com/rancher/longhorn/issues/161
=> Check backup status before creating

app/controller.go, app/replica.go, util/util.go
#121
They floods the real useful logs.
=> app: Remove excess amount of log for health check

integration/core/test_replica.py, integration/data/test_snapshot.py, replica/client/client.go, replica/replica.go, replica/replica_test.go, replica/rest/model.go, replica/rest/replica.go, replica/server.go, sync/sync.go
=> More ways to remove `removable snapshots`

Dockerfile.dapper
Remove timeout on mkfs command
=> Update volume driver

trash.yml
=> point to latest sparse-tool commit

sync/sync.go
We need to separate prepare and process because prepareRemoveSnapshot() will
mark the snapshot as removed, and if it's blocked by sfold process, user will
see different list of snapshots of two replicas
=> sync: Separate prepare and process remove disk

trash.yml
=> Update vendor to latest sparse-tool commit

frontend/rest/model.go, frontend/rest/router.go, integration/data/common.py, integration/data/frontend.py, integration/data/test_backup.py, trash.yml, vendor/github.com/rancher/convoy/api/response.go, vendor/github.com/rancher/convoy/convoydriver/convoydriver.go, vendor/github.com/rancher/convoy/logging/logging.go, vendor/github.com/rancher/convoy/objectstore/config.go, vendor/github.com/rancher/convoy/objectstore/deltablock.go, vendor/github.com/rancher/convoy/objectstore/driver.go, vendor/github.com/rancher/convoy/objectstore/objectstore.go, vendor/github.com/rancher/convoy/objectstore/singlefile.go, vendor/github.com/rancher/convoy/s3/s3.go, vendor/github.com/rancher/convoy/s3/s3_service.go, vendor/github.com/rancher/convoy/util/util.go, vendor/github.com/rancher/convoy/vfs/vfs_objectstore.go
Also fix #202 , as well as test case for it.
=> REST frontend improvement

frontend/fusedev/fuse.go
Wait for 1s * 5 times maximum.
=> fuse: Retry if loopback device wasn't detached immediately

trash.yml, vendor/github.com/rancher/sparse-tools/sparse/client.go, vendor/github.com/rancher/sparse-tools/sparse/file.go, vendor/github.com/rancher/sparse-tools/sparse/rest/handlers.go, vendor/github.com/rancher/sparse-tools/sparse/sfold.go
sfold issue fix: https://github.com/rancher/longhorn/issues/211
ssync file read optimization
@yasker
=> update vendor sparse changes

integration/core/test_cli.py
@yasker 
add a test case for sfolding empty snapshot to its parent
https://github.com/rancher/longhorn/issues/211
=> add a test case for sfolding empty snapshot to its parent

Dockerfile.dapper, app/controller_tgt.go, controller/control.go, frontend/fusedev/frontend.go, frontend/fusedev/fuse.go, frontend/rest/frontend.go, frontend/tcmu/frontend.go, frontend/tgt/frontend.go, integration/core/test_cli.py, integration/core/test_controller.py, integration/data/common.py, integration/data/frontend.py, package/Dockerfile, package/launch-simple-longhorn, scripts/integration-test, scripts/package, trash.yml, types/types.go, util/util.go, vendor/github.com/yasker/go-iscsi-helper/.gitignore, vendor/github.com/yasker/go-iscsi-helper/Dockerfile.dapper, vendor/github.com/yasker/go-iscsi-helper/LICENSE, vendor/github.com/yasker/go-iscsi-helper/Makefile, vendor/github.com/yasker/go-iscsi-helper/README.md, vendor/github.com/yasker/go-iscsi-helper/iscsi/initiator.go, vendor/github.com/yasker/go-iscsi-helper/iscsi/target.go, vendor/github.com/yasker/go-iscsi-helper/trash.conf, vendor/github.com/yasker/go-iscsi-helper/util/util.go
=> TGT frontend

Dockerfile.dapper, trash.yml, util/util.go, vendor/github.com/yasker/go-iscsi-helper/iscsi/initiator.go
1. Retry for delete discovered record on iscsiadm
2. Fix a bug in go-iscsi-helper result in wrong device parsing with iscsiadm.
=> Various TGT fixes related to iscsiadm

Dockerfile.dapper, rpc/server.go, rpc/types.go, util/scsi.go
Fixes #230 
The context of the fix is in TGT and Liblonghorn.
=> TGT fixes for timeout and refactors

Dockerfile.dapper, backend/file/file.go, backend/remote/remote.go, controller/control.go, controller/replicator.go, integration/data/cmd.py, integration/data/common.py, integration/data/test_ha.py, package/Dockerfile, replica/replica.go, replica/rest/model.go, replica/rest/replica.go, replica/rest/router.go, replica/revision_counter.go, replica/server.go, scripts/integration-test, types/types.go
=> Replica revision counter

Dockerfile.dapper, app/backup.go, integration/core/test_cli.py, integration/data/common.py, integration/data/test_backup.py, integration/tox.ini, scripts/integration-test, sync/agent/process.go, types/types.go, vendor.conf, vendor/github.com/rancher/backupstore/s3/s3_service.go
Including:
- Fix validate credential for s3 backup restore.
- Add AWS_ENDPOINTS to support Minio server.
- Make integration test to support both vfs and s3 backup.
=> Enable S3 backup

main.go, scripts/build, scripts/version, version.go
It provides information for compatiability usage as well.
=> app: Add version subcommand

integration/data/test_snapshot.py
With the new snapshot testing interface.
=> test: Update test_snapshot_rm_rolling()

replica/replica.go
Not all file systems support file extent mapping, So replica
should error out if the underlying filesystem does not support
extent mapping.
This commit add check for the extent mapping support.
This can be verified if the given path to the replica is formated
into the file-system which does not give file extent map. Few of
such file-system are NFS, ZFS etc.
Signed-off-by: Utkarsh Mani Tripathi <utkarsh.tripathi@mayadata.io>
=> replica: error out replica if underlying file system doesn't support extent mapping

Dockerfile.dapper
https://github.com/rancher/longhorn/issues/324
=> build: update TGT to support more than 2TB

Dockerfile.dapper, vendor.conf, vendor/github.com/rancher/go-iscsi-helper/Dockerfile.dapper, vendor/github.com/rancher/go-iscsi-helper/iscsi/target.go
Fixes https://github.com/rancher/longhorn/issues/421
=> redirect tgtd log into stderr

backend/remote/remote.go
Fixes https://github.com/rancher/longhorn/issues/420
=> controller: log the detail error with remote backend

app/backup.go, app/restore_to_file.go, integration/data/cmd.py, integration/data/test_restore_to_file.py, main.go
https://github.com/rancher/longhorn/issues/422#issuecomment-471714574
=> Rename restore-to command to restore-to-file and put it under backup subcommand

Dockerfile.dapper
The longhorn-engine-launcher code is updated to the latest and is merged to the master.
Using that commit id in the following dapper file for it to be packaged in engine image.
=> Updating the launcher with the latest commit

controller/control.go, iscsi/iscsi.go, util/util.go
https://github.com/rancher/longhorn/issues/507
=> Snapshot sync in the host namespace

util/util.go, vendor.conf, vendor/github.com/rancher/go-iscsi-helper/util/process.go
https://github.com/rancher/longhorn/issues/501
=> util: FindAncestorByName() check both 'dockerd' and 'containerd'

replica/backup.go
https://github.com/rancher/longhorn/issues/568
=> Fix issue HasSnapshot() cannot find last snapshot

integration/data/cmd.py, integration/data/test_backup.py, vendor.conf, vendor/github.com/longhorn/backupstore/backupstore.go, vendor/github.com/longhorn/backupstore/deltablock.go, vendor/github.com/longhorn/backupstore/list.go
Reverts longhorn/longhorn-engine#397
Cannot pass engine integration test.
=> Revert "Add a test case for empty backup volume"

Dockerfile.dapper, vendor.conf, vendor/github.com/longhorn/longhorn-instance-manager/types/command.go, vendor/github.com/longhorn/longhorn-instance-manager/types/test.go, vendor/github.com/longhorn/longhorn-instance-manager/types/types.go
To 56bbde738123d75ae98b2a5cd17b82fc991d937a
Fixed some deadlocks.
=> Update instance manager

integration/core/common.py, integration/core/test_controller.py, integration/data/test_backup.py, integration/data/test_restore_inc.py, integration/data/test_restore_to_file.py
https://github.com/longhorn/longhorn/issues/646
=> Fix issue: tgt fails to access backend data in integration test

Dockerfile.dapper, integration/core/common.py, integration/data/setting.py, integration/instance/common.py, integration/instance/test_launcher_basic.py, integration/tox.ini, scripts/integration-test
https://github.com/longhorn/longhorn/issues/634
=> Cleanup iscsi sessions after integration test complete/crashed

Dockerfile.dapper, integration/core/common.py, integration/data/setting.py, integration/instance/common.py, integration/instance/test_launcher_basic.py, integration/tox.ini, scripts/integration-test
Included PR:
https://github.com/longhorn/longhorn-engine/pull/411
=> Merge pr from `staging` to `master` with modifications for iscsi session cleanup

app/add_replica.go, main.go, sync/sync.go
The manager is going to use the command to start the controller sooner.
=> Add `start-with-replicas` command

Dockerfile.dapper, vendor.conf
Fix the lost event from engine
=> Update instance manager to 5022f934cb6e6aec01b5729e374b2901422298ed

Dockerfile.dapper, sync/backup.go, sync/sync.go, vendor.conf
https://github.com/longhorn/longhorn/issues/715
=> Fix excessive error message when detaching volume or replica is in ERR

Dockerfile.dapper, vendor.conf
=> Update Instance Manager to f83d29eee6b9451fe5aae1843fa0c2907fd31ffa

replica/client/client.go, sync/rpc/server.go
https://github.com/longhorn/longhorn/issues/779
=> Fix deadlock in purge status

sync/rpc/server.go
=> sync: Fix a potential deadlock caused by failed to initiate the restoration

package/launch-simple-file, package/launch-simple-longhorn
=> package: Fix launch-simple-longhorn script

controller/control.go
https://github.com/longhorn/longhorn/issues/778
=> controller: Stop backupList from holding the data path lock

vendor.conf, vendor/github.com/longhorn/backupstore/backupstore.go
https://github.com/longhorn/longhorn/issues/768
=> Update backupstore to 252c5823a08386c738dcadfc52ee0b1838108c5b

app/backup.go
https://github.com/longhorn/longhorn/issues/774
=> Use the error msg in backup status to decide if removing the backup status is needed

vendor.conf, vendor/github.com/longhorn/backupstore/s3/s3_service.go
=> Update backupstore to 50aa0d32880963015d19c640c5328153da097984

Dockerfile.dapper, frontend/tcmu/cfunc.go, sync/backup.go, sync/rpc/server.go
=> build: Upgrade golang to v1.13.2

go.mod, go.sum, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/879
=> vendor: Update longhorn/go-iscsi-helper to 9143c9e

go.mod, go.sum, vendor/github.com/longhorn/backupstore/util/util.go, vendor/modules.txt
=> Update backupstore to 3524b8ae9518014b544ffaaf9c3ece22a87836f9

integration/core/common.py, integration/core/conftest.py, scripts/integration-test
=> test: start instance manager for engine separately for the test

integration/instance/test_launcher_basic.py
=> test: Fix flake8

integration/common/core.py, integration/data/test_upgrade.py, integration/instance/test_launcher_basic.py, pkg/engine/frontend/tgt/frontend.go, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go
=> test: Fix upgrade

vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go
=> fix wrong log message

go.mod, go.sum, package/engine-manager, package/launch-simple-longhorn, vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go, vendor/github.com/longhorn/go-iscsi-helper/iscsi/target.go, vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/1037
=> Start tgtd automatically for engine manager

package/Dockerfile, scripts/package
=> package longhorn-instance-manager in the engine image

pkg/sync/rpc/server.go
=> Rebuild state is wrongly updated to complete after file sending failure

pkg/sync/rpc/server.go
https://github.com/longhorn/longhorn/issues/1162
=> sync: fix NPE on replica when failed to start restoration

pkg/sync/backup.go
https://github.com/longhorn/longhorn/issues/1166
=> sync: Add ReplicaAddress to the BackupStatus

app/cmd/controller.go, app/cmd/replica.go, app/cmd/shutdown.go, pkg/controller/control.go
https://github.com/longhorn/longhorn/issues/666
=> app: Don't always return exit code 1

go.mod, go.sum, vendor/github.com/longhorn/backupstore/nfs/nfs.go, vendor/github.com/longhorn/go-iscsi-helper/util/util.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/1177
=> Update backupstore and go-iscsi-helper

.gitignore
=> Ignore goland project folders and files

go.mod, go.sum, integration/common/core.py, integration/data/conftest.py, integration/data/test_basic_ops.py, vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go, vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go, vendor/github.com/longhorn/go-iscsi-helper/util/util.go, vendor/modules.txt
Also added an integration test for correct device selection & creation
which was the underlying problem of longhorn/longhorn#1223
=> Update go-iscsi-helper to get fix for #1223

pkg/controller/control.go, pkg/replica/replica.go, pkg/replica/revision_counter.go
=> Fix the revision counter for the upgrade engine

integration/common/frontend.py, integration/data/test_upgrade.py
=> integration test: Add endpoint check after live upgrade

integration/data/test_upgrade.py
https://github.com/longhorn/longhorn/issues/1248
=> integration: Exactly check what the endpoint value is

app/cmd/backup.go
Only a replica in RW mode can create backups, so there is no point in
checking other replicas for their backup status.
longhorn/longhorn#1230
=> Remove no longer known replicas from the backup status check

go.mod, go.sum, integration/data/test_backup.py, vendor/github.com/longhorn/backupstore/deltablock.go, vendor/github.com/longhorn/backupstore/s3/s3_service.go, vendor/modules.txt
=> Update longhorn/backupstore to v0.0.0-20200502041801-8d1f61550db9

go.mod, go.sum, integration/common/core.py, integration/data/test_backup.py, vendor/github.com/longhorn/backupstore/deltablock.go, vendor/github.com/longhorn/backupstore/logging/logging.go, vendor/modules.txt
We had some issues with incremental / full backups, this test covers
cases where we create a duplicate volume for a prior existing volume
longhorn/longhorn#1294
longhorn/backupstore#34
=> Add integration test for incremental backup logic

integration/common/core.py, pkg/sync/rpc/server.go
https://github.com/longhorn/longhorn/issues/1261
=> sync: Fix deleting snapshot progress showing over 100%

go.mod, go.sum, integration/core/test_cli.py, vendor/github.com/longhorn/backupstore/list.go, vendor/github.com/longhorn/backupstore/logging/logging.go, vendor/github.com/longhorn/backupstore/util/util.go, vendor/modules.txt
longhorn/backupstore#35
longhorn/longhorn#1212
=> Add integration test for corrupt s3 backup config

integration/core/test_cli.py, pkg/controller/control.go, pkg/controller/replicator.go
longhorn/longhorn#995
longhorn/longhorn#1253
=> The engine will mark the replica as ERROR if the related backend creation fails

Dockerfile.dapper
=> Update instance manager to 7d0d17b63f653fb17ec188eefe05fe444e7199e9

go.mod, go.sum, integration/common/core.py, integration/core/test_cli.py, pkg/controller/control.go, pkg/frontend/rest/frontend.go, pkg/frontend/socket/frontend.go, pkg/frontend/tgt/frontend.go, pkg/types/types.go, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go, vendor/modules.txt
=> Refactor the frontend start functions and add cleanup during the frontend init

go.mod, go.sum, integration/core/test_cli.py, vendor/github.com/longhorn/backupstore/config.go, vendor/github.com/longhorn/backupstore/deltablock.go, vendor/github.com/longhorn/backupstore/fsops/fsops.go, vendor/github.com/longhorn/backupstore/list.go, vendor/github.com/longhorn/backupstore/util/util.go, vendor/modules.txt
longhorn/longhorn#1341
longhorn/longhorn#1326
=> Update longhorn/backupstore to v0.0.0-20200522215414-07325fbd9a81

go.mod, go.sum, vendor/github.com/longhorn/backupstore/config.go, vendor/github.com/longhorn/backupstore/deltablock.go, vendor/modules.txt
This fixes the in progress backups.
longhorn/longhorn#1399
=> Update backupstore to v0.0.0-20200523213440-51dc4f4f8786

go.mod, go.sum, vendor/github.com/longhorn/backupstore/deltablock.go, vendor/modules.txt
=> Update backupstore v0.0.0-20200530020211-e71b773c1805

go.mod, go.sum, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/1408
=> Update go-iscsi-helper to v0.0.0-20200601183015-ca8b762c2f38

Dockerfile.dapper, buf.yaml, generate_grpc.sh, integration/common/core.py, integration/core/test_cli.py, integration/core/test_replica.py, integration/data/test_ha.py, integration/rpc/replica/replica_client.py, integration/rpc/replica/replica_pb2.py, integration/rpc/replica/replica_pb2_grpc.py, pkg/backend/remote/remote.go, pkg/replica/client/client.go, pkg/replica/rpc/server.go, pkg/sync/backup.go, pkg/sync/rpc/server.go, proto/ptypes/replica.pb.go, proto/ptypes/replica.proto, proto/ptypes/syncagent.pb.go, proto/ptypes/syncagent.proto
https://github.com/longhorn/longhorn/issues/1197
=> Correct gRPC naming for replica and syncagent services

package/launch-simple-longhorn
=> package: Update launch-simple-longhorn to wait for the replica

go.mod, go.sum, vendor/github.com/longhorn/backupstore/deltablock.go, vendor/modules.txt
This fix makes sure that Garbage Collector process does not blocking the UI from responding to the user.
longhorn/longhorn#1471
longhorn/longhorn#1472
=> update backupstore to v0.0.0-20200707024652-0c3469599873

go.mod, go.sum, integration/data/test_backup.py, vendor/github.com/longhorn/backupstore/deltablock.go, vendor/github.com/longhorn/backupstore/driver.go, vendor/github.com/longhorn/backupstore/fsops/fsops.go, vendor/github.com/longhorn/backupstore/lock.go, vendor/github.com/longhorn/backupstore/s3/s3.go, vendor/modules.txt
longhorn/longhorn#612
longhorn/backupstore#45
=> Update backupstore to v0.0.0-20200710011907-69879c2bc9b8 - Filelocks

go.mod, go.sum, vendor/github.com/longhorn/backupstore/README.md, vendor/github.com/longhorn/backupstore/nfs/nfs.go, vendor/github.com/longhorn/backupstore/util/util.go, vendor/modules.txt
This update is mainly for the build fixed in backupstore
https://github.com/longhorn/longhorn/issues/1556
=> update backupstore to v0.0.0-20200710205904-313bf938e2d6

go.mod, go.sum, pkg/sync/rpc/server.go, pkg/types/types.go, pkg/util/util.go, vendor/github.com/longhorn/backupstore/s3/s3_service.go, vendor/modules.txt
=>  Support virtual-hosted-style access for S3 compatible storage

go.mod, go.sum, vendor/github.com/longhorn/backupstore/config.go, vendor/github.com/longhorn/backupstore/list.go, vendor/modules.txt
longhorn/longhorn#710
longhorn/longhorn#1604
=> Update backupstore to v0.0.0-20200717215103-739d80bd783e

Dockerfile.dapper, integration/instance/test_launcher_basic.py
=> Update instance manager and add a test for process creation failure case

pkg/replica/replica.go
https://github.com/longhorn/longhorn/issues/1615
=> replica: Fix a typo for the error message

.drone.yml
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>
=> Update Drone slack notifications instance URL

.drone.yml, README.md
We got issues with Longhorn drone at the moment.
=> Update to use Rancher drone

pkg/backend/remote/remote.go
Possible improvement in the readability of having switch statements instead of long if statement.
=> Replace long if statement with switch statement

go.mod, go.sum, integration/common/cmd.py, integration/common/core.py, integration/core/test_cli.py, integration/data/test_backup.py, vendor/github.com/longhorn/backupstore/.drone.yml, vendor/github.com/longhorn/backupstore/README.md, vendor/github.com/longhorn/backupstore/backupstore.go, vendor/github.com/longhorn/backupstore/deltablock.go, vendor/github.com/longhorn/backupstore/driver.go, vendor/github.com/longhorn/backupstore/fsops/fsops.go, vendor/github.com/longhorn/backupstore/lock.go, vendor/github.com/longhorn/backupstore/s3/s3.go, vendor/modules.txt
=> Backupstore file locks

pkg/controller/client/controller_client.go
Fix incorrect error message for the gRPC health check.
=> Fix incorrect error message for the gRPC health check

go.mod, go.sum, pkg/controller/rebuild.go, pkg/replica/client/client.go, pkg/sync/rpc/server.go, pkg/util/util.go
Hi,
A small MR to handle IPv6 addresses.
PS: I would need to update mod.go once https://github.com/longhorn/go-iscsi-helper/pull/35 is merged i suppose ?
Cheers
=> Add support for IPv6

pkg/sync/backup.go
Variable sequence corrections and improve readability.
=> Fix error message

app/cmd/backup.go, app/cmd/controller.go, app/cmd/ls_replica.go, app/cmd/rm_replica.go, app/cmd/snapshot.go, app/cmd/stats.go, app/cmd/volume.go
Rename `getCli` to `getControllerClient` and move to `controller.go` to resonate method purpose.
=> Rename getCli to getControllerClient

app/cmd/backup.go
Fix CLI usage messages.
Ref: https://github.com/longhorn/longhorn-engine/pull/539
=> Fix CLI restore message

go.mod, go.sum, integration/data/test_backup.py, vendor/github.com/longhorn/backupstore/.drone.yml, vendor/github.com/longhorn/backupstore/README.md, vendor/github.com/longhorn/backupstore/backupstore.go, vendor/github.com/longhorn/backupstore/deltablock.go, vendor/github.com/longhorn/backupstore/driver.go, vendor/github.com/longhorn/backupstore/fsops/fsops.go, vendor/github.com/longhorn/backupstore/lock.go, vendor/github.com/longhorn/backupstore/s3/s3.go, vendor/github.com/longhorn/backupstore/util/util.go, vendor/modules.txt
=> Add backup locks support

integration/common/core.py, integration/core/conftest.py, integration/core/test_cli.py, integration/data/conftest.py, integration/data/test_upgrade.py, integration/instance/test_launcher_basic.py, integration/rpc/controller/controller_client.py
https://github.com/longhorn/longhorn/issues/6
=> Add engine controller and replica client work around for arm support.

pkg/sync/sync.go
=> Enhance error message

.drone.yml, Dockerfile.dapper, integration/data/conftest.py, package/Dockerfile, scripts/package
https://github.com/longhorn/longhorn/issues/6
=> ARM64 support for longhorn engine

Dockerfile.dapper
https://github.com/longhorn/longhorn/issues/1854
=> build: update instance manager to v1_20201021

go.mod, go.sum, vendor/github.com/longhorn/sparse-tools/sparse/file.go, vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go, vendor/modules.txt
=> vendor: Update longhorn/sparse-tools to bb457e1

go.mod, go.sum, vendor/github.com/longhorn/backupstore/s3/s3_service.go, vendor/modules.txt
=> vendor: update github.com/longhorn/backupstore to v0.0.0-20201203004625-fdbdd88b09d6

pkg/sync/sync.go
There are 2 callers of the SnapshotPurge command:
1. From Longhorn manager API
2. After finish rebuilding a new replica and `Automatically Cleanup System Generated Snapshot` setting is on
This PR make sure that the error when start SnapshotPurge is reported back to Longhorn manager. It makes debugging easier.
longhorn/longhorn#1895
=> pkg/sync: return error when fail to start snapshot purge on one of the replicas

go.mod, go.sum, vendor/github.com/longhorn/backupstore/s3/s3_service.go, vendor/modules.txt
Bump longhorn/backupstore version to support s3 pagination.
https://github.com/longhorn/longhorn/issues/1904
=> Support s3 pagination

README.md
update readme to resolve ticket '[BUG] fix longhorn readme on command launch docker cluster' (#)
Signed-off-by: Clark Hsu <clark.hsu@suse.com>
=> update readme (#)

go.mod, go.sum, pkg/sync/rpc/server.go, vendor/github.com/longhorn/sparse-tools/cli/ssync/main.go, vendor/github.com/longhorn/sparse-tools/sparse/client.go, vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go, vendor/github.com/longhorn/sparse-tools/sparse/rest/server.go, vendor/github.com/longhorn/sparse-tools/stats/stats.go, vendor/modules.txt
=> vendor: Update longhorn/sparse-tools

.drone.yml
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>
https://github.com/longhorn/longhorn/issues/1961
=> automatically build necessary engine images for test

go.mod, go.sum, vendor/github.com/longhorn/backupstore/driver.go, vendor/github.com/longhorn/backupstore/list.go, vendor/modules.txt
=> [BACKPORT] Bump longhorn/backupstore to enhance read volume backups performance

go.mod, go.sum, vendor/github.com/longhorn/backupstore/driver.go, vendor/github.com/longhorn/backupstore/list.go, vendor/modules.txt
=> Bump longhorn/backupstore to enhance read volume backups performance

drone-manifest.tmpl
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>
=> modify manifest file

drone-manifest.tmpl
Reverts longhorn/longhorn-engine#607
=> Revert "modify manifest file"

.drone.yml
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>
=> add upgrade test image steps

pkg/controller/multi_writer_at.go
This makes MultiWriteAt.WriteAt return len(p) if at least one of the WriteAt's to the replicas was successful.  Previously, if at least one of the WriteAt's failed, it would return 0.  This change has no impact to the behavior of longhorn-engine.
=> Return a non-zero value of one of the WriteAts is successful.

go.mod, go.sum, vendor/github.com/longhorn/sparse-tools/sparse/client.go, vendor/github.com/longhorn/sparse-tools/sparse/file.go, vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go, vendor/github.com/longhorn/sparse-tools/sparse/sfold.go, vendor/github.com/longhorn/sparse-tools/sparse/util.go, vendor/modules.txt
depends on https://github.com/longhorn/sparse-tools/pull/76
Signed-off-by: Joshua Moody <joshua.moody@suse.com>
=> Update sparse-tools to get replica rebuild enhancement

go.mod, go.sum, vendor/github.com/longhorn/backupstore/list.go, vendor/modules.txt
Bump longhorn/backupstore version to fix list in progress backup panic
https://github.com/longhorn/longhorn/issues/2683
Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>
=> Bump longhorn/backupstore version to fix list in progress backup panic

go.mod, go.sum, vendor/github.com/longhorn/backupstore/list.go, vendor/modules.txt
Bump longhorn/backupstore version to fix list in progress backup panic
https://github.com/longhorn/longhorn/issues/2683
Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>
=> [cherry-pick-v1.1.2] Bump longhorn/backupstore version to fix list in progress backup panic

pkg/controller/client/controller_client.go, pkg/replica/backup.go, pkg/replica/client/client.go, pkg/replica/extents.go, pkg/sync/rpc/server.go
=> Speed up backup creation: Avoid using channel in CompareSnapshot

pkg/controller/client/controller_client.go, pkg/replica/backup.go, pkg/replica/client/client.go, pkg/replica/extents.go, pkg/sync/rpc/server.go
=> BACKPORT: Speed up backup creation: Avoid using channel in CompareSnapshot

Dockerfile.dapper, go.mod, go.sum, package/Dockerfile, vendor/github.com/satori/go.uuid/.travis.yml, vendor/github.com/satori/go.uuid/LICENSE, vendor/github.com/satori/go.uuid/README.md, vendor/github.com/satori/go.uuid/codec.go, vendor/github.com/satori/go.uuid/generator.go, vendor/github.com/satori/go.uuid/sql.go, vendor/github.com/satori/go.uuid/uuid.go, vendor/modules.txt
ref: 
- https://ci.longhorn.io/job/private/job/image-security-scan/359/
- https://github.com/longhorn/longhorn/issues/2763
cc @meldafrawi
=> Update go package to resolve vulnerability issues

integration/core/test_cli.py
https://github.com/longhorn/longhorn/issues/1628
=> Add test for removing a replica and recreating it

Dockerfile.dapper, package/Dockerfile
=> Add instance manager cli back to engine image

app/cmd/add_replica.go, app/cmd/backup.go, app/cmd/controller.go, app/cmd/ls_replica.go, app/cmd/rm_replica.go, app/cmd/snapshot.go, app/cmd/stats.go, app/cmd/sync_agent.go, app/cmd/volume.go, pkg/controller/client/controller_client.go, pkg/controller/rebuild.go, pkg/controller/revert.go, pkg/replica/client/client.go, pkg/sync/backup.go, pkg/sync/rpc/server.go, pkg/sync/sync.go, pkg/util/once.go, pkg/util/once_test.go, version.go
=> Backport 2818 - Optimize GRPC client sockets to allow for reuse

pkg/backend/remote/remote.go
The ping timeout was occurring in scenarios with limited bandwidth and
high network usage.  The limited bandwidth and high network traffic was
delaying the transmission of the ping message and the response, causing
the timeout to occur when the replica was in fact operational.
Without the ping timeout, the code can still take advantage of the
default TCP keep alive timeout that golang's networking code sets to 15
seconds.  The TCP keep alive timeout is a socket option whose
functionality is implemented by the Linux kernel.
https://github.com/longhorn/longhorn/issues/2882
=> Remove ping timeout

pkg/backend/remote/remote.go
The ping timeout was occurring in scenarios with limited bandwidth and
high network usage.  The limited bandwidth and high network traffic was
delaying the transmission of the ping message and the response, causing
the ping timeout to occur when the replica was in fact operational.
Without the ping timeout, the code can still take advantage of the
default TCP keep alive timeout that golang's networking code sets to 15
seconds.  The TCP keep alive timeout is a socket option whose
functionality is implemented by the Linux kernel.
https://github.com/longhorn/longhorn/issues/2882
=> Remove ping timeout v1.1.3 backport

pkg/sync/backup.go
=> sync: Make sure there is only 1 snapshot before restore

go.mod, go.sum, vendor/github.com/longhorn/backupstore/nfs/nfs.go, vendor/modules.txt
Set NFS mount option actimeo to 1 second
https://github.com/longhorn/longhorn/issues/2926
=> Bump longhorn/backupstore version

go.mod, go.sum, vendor/github.com/longhorn/backupstore/nfs/nfs.go, vendor/modules.txt
Set NFS mount option `actimeo` to 1 second
https://github.com/longhorn/longhorn/issues/2926
=> [v1.2.x] Bump longhorn/backupstore version

pkg/controller/control.go
=> Backport v1.1.3 fsfreeze removal

pkg/controller/control.go, pkg/dataconn/server.go
Signed-off-by: Shatakshi <shatakshi.gupta85@gmail.com>
Related to Bugbash.
=> Fix staticcheck issues

pkg/controller/control.go
Remove unused function unfreezeFilesystem.
Signed-off-by: Nisha K <nishak@vmware.com>
=> Remove unused function

app/cmd/replica.go, pkg/backend/remote/remote.go, pkg/replica/rpc/dataserver.go
=> Update longhorn engine

Dockerfile.dapper
https://github.com/longhorn/longhorn/issues/3636
=> Update liblonghorn version

Dockerfile.dapper, package/Dockerfile, scripts/package
Ref: https://github.com/longhorn/longhorn/issues/2939
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>
=> change base image to SUSE BCI

pkg/controller/rebuild.go
https://github.com/longhorn/longhorn/issues/3822
=> Check that array isn't empty before accessing

go.mod, go.sum, integration/common/core.py, integration/common/frontend.py, integration/core/test_replica.py, integration/data/test_snapshot.py, pkg/controller/rebuild.go, pkg/controller/revert.go, pkg/controller/util.go, pkg/replica/replica.go, pkg/replica/replica_test.go, pkg/sync/rpc/server.go, pkg/util/util.go, vendor/github.com/longhorn/sparse-tools/sparse/sprune.go, vendor/github.com/longhorn/sparse-tools/sparse/util.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/3613
https://github.com/longhorn/longhorn/issues/3748
=> Snapshot prune feature & snapshot revert improvement

go.mod, go.sum, integration/common/core.py, integration/common/frontend.py, integration/core/test_replica.py, integration/data/test_snapshot.py, pkg/controller/rebuild.go, pkg/controller/revert.go, pkg/controller/util.go, pkg/replica/replica.go, pkg/replica/replica_test.go, pkg/sync/rpc/server.go, pkg/util/util.go, vendor/github.com/longhorn/sparse-tools/sparse/client.go, vendor/github.com/longhorn/sparse-tools/sparse/file.go, vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go, vendor/github.com/longhorn/sparse-tools/sparse/sprune.go, vendor/github.com/longhorn/sparse-tools/sparse/util.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/3613
https://github.com/longhorn/longhorn/issues/3748
https://github.com/longhorn/longhorn/issues/3764
=> [Backport][v1.1.4] Snapshot prune feature & snapshot revert improvement

go.mod, go.sum, integration/common/core.py, integration/common/frontend.py, integration/core/test_replica.py, integration/data/test_snapshot.py, pkg/controller/rebuild.go, pkg/controller/revert.go, pkg/controller/util.go, pkg/replica/replica.go, pkg/replica/replica_test.go, pkg/sync/rpc/server.go, pkg/util/util.go, vendor/github.com/longhorn/sparse-tools/sparse/sprune.go, vendor/github.com/longhorn/sparse-tools/sparse/util.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/3613
https://github.com/longhorn/longhorn/issues/3748
https://github.com/longhorn/longhorn/issues/3768
=> [Backport][v1.2.5] Snapshot prune feature & snapshot revert improvement

.drone.yml, Dockerfile.dapper, pkg/dataconn/wire.go, scripts/package
This PR adds support to build on s390x architecture.
=> Add s390x support

pkg/sync/rpc/server.go
=> Fix bug volume cloning is broken because of failing to revert snapshot

Dockerfile.dapper
[Longhorn 4032](https://github.com/longhorn/longhorn/issues/4032)
=> Fix the protobuf-python version

integration/data/test_snapshot.py
https://github.com/longhorn/longhorn/issues/4089
=> Skip flaky 'test_snapshot_mounted_filesystem' temporarily

Dockerfile.dapper, package/Dockerfile
https://github.com/longhorn/longhorn/issues/4191
https://github.com/longhorn/longhorn-engine/pull/714
=> [BACKPORT][v1.3.x] update devel tool scm

pkg/sync/rpc/server.go, pkg/sync/sync.go
https://github.com/longhorn/longhorn/issues/4183
https://github.com/longhorn/longhorn/issues/4252
=> [BACKPORT][v1.2.x] Check purge status before rebuilding a replica

pkg/sync/rpc/server.go, pkg/sync/sync.go
https://github.com/longhorn/longhorn/issues/4183
https://github.com/longhorn/longhorn/issues/4251
=> [BACKPORT][v1.3.x] Check purge status before rebuilding a replica

Dockerfile.dapper, package/Dockerfile
Depends on https://github.com/rancher/tgt/pull/8 and https://github.com/rancher/liblonghorn/pull/16
[Longhorn 4136](https://github.com/longhorn/longhorn/issues/4136)
=> Add tcmalloc for amd64 platform

integration/data/test_snapshot.py
[Longhorn 4089](https://github.com/longhorn/longhorn/issues/4089)
=> Enable test_snapshot_mounted_filesystem

pkg/controller/control.go
In the 3 nodes k8s environment, if longhorn use the setting of storage-network, and the second network is contronllerd by ovs-cni,  there is 3 instance-manager of replica, and the instance-manager of replica may have the same storage ip address. And now we create a volume whit 2 replicas, the instance-manager of engine may connect to the 2 instance-manager of replica with the same  ip address, this will make some mistake, and we can see the log below(In the log the error is caused by network, but  ip address duplication is still a problem ). So i add some code to judge whether the address of instance-manager-r is duplicated.
`[longhorn-instance-manager] time="2022-07-09T07:12:39Z" level=info msg="Process Manager: created process vol111-e-52d90c97"
[vol111-e-52d90c97] …
=> Add a code to judge whether the address is duplicate

go.mod, go.sum, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/4364
=> [BACKPORT][v1.2.x] vendor: update go-iscsi-helper

go.mod, go.sum, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/4363
=> [BACKPORT][v1.3.x] improve err when failed to init frontend

pkg/sync/sync.go
https://github.com/longhorn/longhorn/issues/4294
https://github.com/longhorn/longhorn/issues/4365
=> [Backport][v1.3.x] sync: Improve log for the snapshot purge call

go.mod, go.sum, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/4362
=> vendor: update go-iscsi-helper

pkg/sync/sync.go
=> sync: Improve log for the snapshot purge call

pkg/sync/sync.go
https://github.com/longhorn/longhorn/issues/4294
https://github.com/longhorn/longhorn/issues/4373
=> [Backport][v1.2.x] sync: Improve log for the snapshot purge call

pkg/backend/file/file.go, pkg/backend/remote/remote.go, pkg/controller/control.go, pkg/dataconn/client.go, pkg/sync/sync.go, pkg/types/types.go
https://github.com/longhorn/longhorn/issues/4212
https://github.com/longhorn/longhorn/issues/4484
Signed-off-by: Derek Su [derek.su@suse.com](mailto:derek.su@suse.com)
=> [BACKPORT][v1.2.5] Mark the replica ERR if its volume.meta is in invalid state 

pkg/backend/file/file.go, pkg/backend/remote/remote.go, pkg/controller/control.go, pkg/dataconn/client.go, pkg/sync/sync.go, pkg/types/types.go
https://github.com/longhorn/longhorn/issues/4212
https://github.com/longhorn/longhorn/issues/4485
Signed-off-by: Derek Su [derek.su@suse.com](mailto:derek.su@suse.com)
=> [BACKPORT][v1.3.2] Mark the replica ERR if its volume.meta is in invalid state 

go.mod, go.sum, vendor/github.com/longhorn/backupstore/nfs/nfs.go, vendor/github.com/longhorn/backupstore/util/util.go, vendor/modules.txt
[Longhorn 4552](https://github.com/longhorn/longhorn/issues/4552)
=> vendor: update longhorn-engine

pkg/controller/control.go
During rebuilding (while we have WO replica), if the incoming IO is not aligned, we read full 4096 bytes blocks from RW replicas then write that to all replicas. This should support all kinds of filesystem logical block sizes well as block volume mode.
longhorn/longhorn#4354
=> Fix data corruption due to COW and block size not being aligned during rebuilding replicas

pkg/controller/control.go
=> [BACKPORT][v1.3.2] Fix data corruption due to COW and block size not being aligned during rebuilding replicas

go.mod, go.sum, vendor/github.com/longhorn/backupstore/nfs/nfs.go, vendor/github.com/longhorn/backupstore/util/util.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/4552
https://github.com/longhorn/longhorn/issues/4580
=> [BACKPORT][v1.3.2] vendor: update backupstore

app/cmd/replica.go, pkg/backingfile/backingfile.go, pkg/replica/replica.go, pkg/replica/server.go, pkg/util/util.go
[Longhorn 4599](https://github.com/longhorn/longhorn-engine)
=> Reorganize volume, replica and backing image sector sizes

pkg/controller/control.go, pkg/controller/control_test.go
=> [BACKPORT][v1.3.2] Fix wrong aligment calculation and written bytes returned and add unit test for writeInWOMode

app/cmd/replica.go, pkg/backingfile/backingfile.go, pkg/replica/replica.go, pkg/replica/server.go, pkg/util/util.go
https://github.com/longhorn/longhorn/issues/4599
https://github.com/longhorn/longhorn/issues/4636
(cherry picked from commit 1d5d3c94c572651c546d29dc074c2a4608adc283) (cherry picked from commit 2bffb129a9ef77f69dfd6e427706f0cb1b6f0420)
=> [BACKPORT][v1.2.6] Reorganize volume, replica and backing image sector sizes

pkg/controller/control.go, pkg/controller/control_test.go
=> Fix wrong aligment calculation and written bytes returned and add unit test for writeInWOMode

pkg/controller/control.go, pkg/controller/control_test.go
=> [BACKPORT][v1.2.6] Fix wrong aligment calculation and written bytes returned and add unit test for writeInWOMode

app/cmd/system_backup.go, go.mod, go.sum, main.go, vendor/github.com/longhorn/backupstore/cmd/system_backup.go, vendor/github.com/longhorn/backupstore/config.go, vendor/github.com/longhorn/backupstore/driver.go, vendor/github.com/longhorn/backupstore/lock.go, vendor/github.com/longhorn/backupstore/logging/logging.go, vendor/github.com/longhorn/backupstore/nfs/nfs.go, vendor/github.com/longhorn/backupstore/s3/s3.go, vendor/github.com/longhorn/backupstore/systembackup/system_backup.go, vendor/github.com/longhorn/backupstore/util/util.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/1455
=> feat(system-backup/restore): new commands

Dockerfile.dapper, app/cmd/controller.go, go.mod, go.sum, package/Dockerfile, pkg/backend/dynamic/dynamic.go, pkg/backend/file/file.go, pkg/backend/remote/remote.go, pkg/controller/control.go, pkg/controller/init_frontend.go, pkg/dataconn/client.go, pkg/frontend/socket/frontend.go, pkg/frontend/tgt/frontend.go, pkg/meta/version.go, pkg/types/types.go, pkg/util/util.go, vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go, vendor/github.com/longhorn/go-iscsi-helper/iscsi/target.go, vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go, vendor/github.com/longhorn/go-iscsi-helper/util/process.go, vendor/github.com/longhorn/go-iscsi-helper/util/util.go, vendor/modules.txt
[Longhorn 4491](https://github.com/longhorn/longhorn/issues/4491)
=> Adjust the iSCSI initiator/target timeout and the engine-to-replica timeout

pkg/replica/hash.go, pkg/replica/replica.go, pkg/sync/rpc/server.go, pkg/util/disk/constant.go, pkg/util/disk/disk.go
https://github.com/longhorn/longhorn/issues/4934
=> Replace the modTime (mtime) with ctime in snapshot hash

app/cmd/controller.go, app/cmd/replica.go, pkg/backend/dynamic/dynamic.go, pkg/backend/file/file.go, pkg/backend/remote/remote.go, pkg/controller/control.go, pkg/replica/rpc/dataserver.go, pkg/types/types.go, pkg/util/util.go
https://github.com/longhorn/longhorn/issues/3957
Signed-off-by: Derek Su [derek.su@suse.com](mailto:derek.su@suse.com)
=> feat: support local volume (data path)

Dockerfile.dapper, package/Dockerfile
Dockerfile: update the path to devel tools repo
For https://github.com/longhorn/longhorn/issues/4949
Signed-off-by: Yang Chiu <yang.chiu@suse.com>
=> Dockerfile: update the path to devel tools repo

go.mod, go.sum, pkg/controller/control.go, pkg/frontend/socket/frontend.go, vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go, vendor/github.com/longhorn/go-iscsi-helper/iscsi/target.go, vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go, vendor/github.com/longhorn/go-iscsi-helper/types/tgtadm_errors.go, vendor/modules.txt
https://github.com/longhorn/longhorn/issues/4959
depends on https://github.com/longhorn/go-iscsi-helper/pull/49
Signed-off-by: Derek Su [derek.su@suse.com](mailto:derek.su@suse.com)
=> Update go-iscsi-helper for error handling

pkg/replica/replica.go, pkg/replica/server.go, pkg/sync/rpc/server.go
[Longhorn 4980](https://github.com/longhorn/longhorn/issues/4980)
=> Fix the misleading log messages

app/cmd/controller.go, main.go, pkg/backend/remote/remote.go, pkg/controller/control.go, pkg/controller/errors.go, pkg/controller/replicator.go, pkg/replica/rest/model.go, pkg/replica/server.go, pkg/sync/sync.go, pkg/types/types.go
[Longhorn 1330](https://github.com/longhorn/longhorn/issues/1330)
=> Return exit code ENODATA(61) if there is no backend when starting controller

Dockerfile.dapper, go.mod, go.sum, package/Dockerfile, pkg/controller/control.go, pkg/frontend/tgt/frontend.go, pkg/replica/replica.go, vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go, vendor/github.com/longhorn/go-iscsi-helper/iscsi/target.go, vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go, vendor/modules.txt
=> Online expansion support

Dockerfile.dapper, package/Dockerfile
=> package: update tcmalloc to 2.10

Dockerfile.dapper, package/Dockerfile
Longhorn/longhorn#5050
Longhorn/longhorn#5051
=> [BACKPORT][v1.3.3] package: update tcmalloc to 2.10

Dockerfile.dapper, package/Dockerfile
=> [BACKPORT][v1.4.x] package: update tcmalloc to 2.10

Dockerfile.dapper, package/Dockerfile
=> Disable tcmalloc

Dockerfile.dapper, package/Dockerfile
=> [BACKPORT][v1.4.0] Disable tcmalloc

go.mod, go.sum, pkg/controller/control.go, pkg/replica/replica.go, vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go, vendor/modules.txt
=> Fix the canceling logic and the upgrade related issues for online expansion

go.mod, go.sum, vendor/github.com/longhorn/sparse-tools/cli/ssync/main.go, vendor/github.com/longhorn/sparse-tools/sparse/client.go, vendor/github.com/longhorn/sparse-tools/sparse/file.go, vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go, vendor/github.com/longhorn/sparse-tools/sparse/rest/server.go, vendor/modules.txt
Longhorn/longhorn#4092
Longhorn/longhorn#5111
=> [BACKPORT][v1.4.0] vendor: update sparse-tools

Dockerfile.dapper, package/Dockerfile
Longhorn/longhorn#5096
https://github.com/longhorn/longhorn/issues/5097
=> [BACKPORT][v1.3.3] Disable tcmalloc

go.mod, go.sum, pkg/controller/control.go, pkg/replica/replica.go, vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go, vendor/modules.txt
=> [Backport][v1.4.x] Fix the canceling logic and the upgrade related issues for online expansion

pkg/replica/replica.go
=> [BACKPORT][V1.4.0] Ignore ENOEXIST if file is not existing in rmDisk

pkg/controller/control.go
=> control: Clear error when the expansion succeeded

pkg/replica/replica.go
=> Ignore ENOEXIST if file is not existing in rmDisk

pkg/controller/control.go
=> Fix the expansion error issue

go.mod, go.sum, vendor/github.com/longhorn/sparse-tools/sparse/client.go, vendor/modules.txt
=> vendor: update sparse-tools

pkg/replica/hash.go
=> Calculate checksums of replicas using direct io

go.mod, go.sum, vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go, vendor/github.com/longhorn/go-iscsi-helper/iscsi/target.go, vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go, vendor/github.com/longhorn/go-iscsi-helper/longhorndev/dev.go, vendor/github.com/longhorn/go-iscsi-helper/types/tgtadm_errors.go, vendor/github.com/longhorn/go-iscsi-helper/util/util.go, vendor/modules.txt
=> [BACKPORT][v1.3.x] vendor: update go-iscsi-helper

integration/data/test_snapshot.py
=> integration: improve filesystem_trim_test

pkg/controller/control.go
=> Fix deadlock when encountering a failed UnmapAt operation

go.mod, go.sum, vendor/github.com/longhorn/backupstore/Dockerfile.dapper, vendor/github.com/longhorn/backupstore/backupstore.go, vendor/github.com/longhorn/backupstore/cmd/list.go, vendor/github.com/longhorn/backupstore/cmd/system_backup.go, vendor/github.com/longhorn/backupstore/config.go, vendor/github.com/longhorn/backupstore/deltablock.go, vendor/github.com/longhorn/backupstore/driver.go, vendor/github.com/longhorn/backupstore/fsops/fsops.go, vendor/github.com/longhorn/backupstore/go.mod, vendor/github.com/longhorn/backupstore/http/client.go, vendor/github.com/longhorn/backupstore/list.go, vendor/github.com/longhorn/backupstore/lock.go, vendor/github.com/longhorn/backupstore/logging/logging.go, vendor/github.com/longhorn/backupstore/nfs/nfs.go, vendor/github.com/longhorn/backupstore/s3/s3.go, vendor/github.com/longhorn/backupstore/s3/s3_service.go, vendor/github.com/longhorn/backupstore/singlefile.go, vendor/github.com/longhorn/backupstore/systembackup/system_backup.go, vendor/github.com/longhorn/backupstore/util/util.go, vendor/github.com/longhorn/backupstore/vfs/vfs.go, vendor/golang.org/x/net/http/httpproxy/proxy.go, vendor/modules.txt
from `20220913112826-5f5c95274f2a` to ~`20230316055339-4879228b1209`~ `20230306022849-8d5e216c3b33`
longhorn/longhorn#5265
Regression test: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3313/
=> vendor: update `backupstore` by v1.3.x branch

go.mod, go.sum, vendor/github.com/longhorn/sparse-tools/sparse/client.go, vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go, vendor/modules.txt
Bump github.com/longhorn/sparse-tools from v0.0.0-20230216042534-6e4173e9def4 to v0.0.0-20230327064700-b60b990a105b
=> [BACKPORT][v1.4.x] chore(deps): bump github.com/longhorn/sparse-tools

pkg/backend/file/file.go, pkg/backend/remote/remote.go, pkg/controller/control.go, pkg/types/types.go
https://github.com/longhorn/longhorn/issues/6626
=> fix: rebuilding in volume.meta blocks engine start

package/Dockerfile, scripts/package
ref: https://github.com/longhorn/longhorn/issues/5911
This is the manual PR to update v1.4.x Dockerfile
=> [Backport 1.4.x ] build: reduce iamge size by introducing multi stage build

package/Dockerfile, scripts/package
ref: https://github.com/longhorn/longhorn/issues/5911
reduce from **756MB** to **392MB**
=> build: reduce the image size by introducing multi stage build

pkg/backend/remote/remote.go, pkg/controller/client/controller_client.go, pkg/replica/client/client.go, pkg/sync/rpc/server.go
https://github.com/longhorn/longhorn/issues/7291
=> refactor: replace deprecated grpc.WithInsecure

pkg/meta/version.go
https://github.com/longhorn/longhorn/issues/5842
=> feat: engine version enforcement

Dockerfile.dapper
https://github.com/longhorn/longhorn/issues/7476
=> ci: combine DAPPER_OUTPUT

Dockerfile.dapper, pkg/meta/version.go
https://github.com/longhorn/longhorn/issues/7555
=> feat: bump CLIAPIVersion to 10

package/Dockerfile
https://github.com/longhorn/longhorn/issues/7523
=> fix(cve): update dependencies

Dockerfile.dapper
N/A
Add SKIP_TASKS to drone env, so it can be respected during drone build.
=> ci: add SKIP_TASKS to drone build

.drone.yml
ref: longhorn/longhorn#8166
Signed-off-by: davidko <dko@suse.com>
=> ci: rollback BCI image to 15.5

Dockerfile.dapper
https://github.com/longhorn/longhorn/issues/6744
https://github.com/longhorn/longhorn-engine/pull/1081#issuecomment-2068079458
=> [V1.6.x] fix: missing rpc from longhorn-instance-manager

Dockerfile.dapper
=> Dockerfile: update golang to 1.22.2

pkg/backend/remote/remote.go, pkg/controller/client/controller_client.go, pkg/replica/client/client.go, pkg/sync/rpc/server.go
=> fix(lint): replace grpc Dial with NewClient

.github/workflows/build.yml, Dockerfile.dapper
=> ci: use golang bci instead of manual download

.github/workflows/build.yml
=> fix(ci): fix wrong tagged build name

package/Dockerfile
Issue longhorn/longhorn#8722, longhorn/longhorn#8721
Refresh and update release image system packages.
- TODO: backport to master and v1.7.x.
`None`
=> build(image): always update system packages

Dockerfile.dapper
=> chore(dockerfile): clone and build correct instance-manager codes for v1.6.x

.github/workflows/build.yml, Dockerfile.dapper, Makefile, scripts/package
Supports security build.
Prepare for potential secure release
The secrets provided by EIO MUST NOT present in any visible output.
Guidance on achieving SLSA Level 3
=> feat: new makefile target for secure image build

package/Dockerfile, scripts/build, scripts/package
=> fix(ci): fix binary dependency for local image packaging

.github/workflows/build.yml, Dockerfile.dapper, Makefile, package/Dockerfile, scripts/build, scripts/package
Backport the following secure PRs to v1.8.x:
- #1403 
- #1427 
- #1428
=> feat(ci): Backport secure build to v1.8.x

Dockerfile.dapper, package/Dockerfile
=> chore(Dockerfile): retry zypper commands if they are failed

go.mod, go.sum, vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go, vendor/modules.txt
Issue longhorn/longhorn#2259
Support for IPv6.
`None`
`None`
=> feat(ipv6): update vendor

.github/workflows/build.yml
=> fix: use ubuntu-24.04-arm for arm64

pkg/sync/rpc/server.go
Issue longhorn/longhorn#11386
Similar to [the engine & replica](https://github.com/longhorn/longhorn-engine/blob/master/pkg/controller/rpc/server.go#L55), expose the profiling control interface, and user can enable/disable pprof server by:
```bash
longhorn --url http://localhost:<sync_agent_port> profiler enable --port <profiler_port>
```
=> feat(backup): expose profiler interface for sync agent

package/Dockerfile
=> fix: outdated SLES repo

main.go
=> feat: improve logging precision to microseconds

.github/workflows/build.yml
=> chore(workflow): support workflow_dispatch with given tag or branch

integration/common/core.py
Issue longhorn/longhorn#11637
`cleanup_controller()` called `volume_shutdown()` but returned immediately without ensuring that the iSCSI frontend had fully torn down. As a result, leftover iSCSI sessions were still active or reconnecting when the test invoked volume_start() to restart the volume.
This PR adds a wait loop in `cleanup_controller()` to ensure that iSCSI sessions are fully cleared before continuing.
`None`
`None`
=> fix(integration): wait for iSCSI session cleanup in cleanup_controller()
