longhorn/longhorn-engine

- frontend/tcmu/cfunc.go
Fix following warnings
frontend/tcmu/cfunc.go: In function 'sh_open_cgo':
frontend/tcmu/cfunc.go:23:9: warning: implicit declaration of function 'shOpen' [-Wimplicit-function-declaration]
return shOpen(dev);
^
frontend/tcmu/cfunc.go: In function 'sh_close_cgo':
frontend/tcmu/cfunc.go:27:2: warning: implicit declaration of function 'shClose' [-Wimplicit-function-declaration]
shClose(dev);
^
> Fix implicat declaration warning in cgo

- frontend/tcmu/cfunc.go
This patch will fix `poll received unexpected revent: 0x0`
This event is harmless, and shouldn't result in TCMU polling failure.
> tcmu: Fix poll return 0

- Dockerfile.dapper
- agent/controller/controller.go
- agent/status/common.go
- agent/status/replica.go
- integration/core/test_cli.py
- sync/sync.go
- In replcia healthcheck: if a replica is not listed in the controller API, consider it healthy.
- Add logic to retry replicas that errored out
- Pull in new docker-longhorn-driver that tweaks the replica
healthcheck configuration
> Replica healthcheck fixes

- Dockerfile.dapper
- frontend/tcmu/cfunc.go
- frontend/tcmu/main.go
A patch for tcmu-runner is needed. So add dependency to `yasker/tcmu-runner`.
Basically tcmu-runner doesn't check if it's the device we want to handle
before open uio device, which caused multiple handlers may contend for the
same uio device(though only one of them should do so).
The patch in tcmu-runner uses check_config to validate the device before
actually open it. Also the handlers in longhorn need to make sure that it only
handle it's own volume, which indicates in dev_config: `longhorn//<volume_name>`
> tcmu: Add check_config before add device

- rpc/client.go
Notes:
- writes are retried
- but direct block write I/O is supposed to be atomic on a block level. So concurrent 'same write' ops idempotence should still hold...
> RW timeout retry

- package/Dockerfile
- package/launch-simple-longhorn
It will start an single replica longhorn system, running with TCMU frontend
inside container. The volume size is 1Gb.
It can be run with:
`docker run -it --privileged -v /dev:/host/dev -v /volume/ rancher/longhorn bash -c "launch-simple-longhorn volume_name"`
> package: launch script for simple version longhorn

- package/Dockerfile
Addresses #201
Had to update share-mnt to work with docker 1.11. The previous version only worked with docker 1.10 and down. The new version is also backwards compatible.
> Update share-mnt to v0.1.2

- frontend/fusedev/fuse.go
It may result in detaching a non-existing loopback device thus error out.
> fuse: Don't put detach in the retry loop

- integration/data/common.py
- integration/data/frontend.py
- package/launch-simple-longhorn
- scripts/integration-test
`fuse` frontend still have issue with direct_io(#207), thus cause time failure from time to time. Switch back to `rest` for now.
> Revert back to use `rest` frontend as default test frontend

- controller/client/controller_client.go
- controller/control.go
- controller/rest/model.go
- controller/rest/replica.go
- controller/rest/router.go
- package/launch
- sync/sync.go
Now we allow snapshot happens during the rebuild, so there are several critical points we need to sync snapshot operation with rebuild operation.
1. The volume head disk metadata file will be used for future snapshots, so it needs to be updated ASAP.
2. The final check of new replica needs to be done without racing against snapshot operation in the process.
This patchset fixes #266
> Improved sync mechanism for rebuild during snapshotting

- app/controller.go
- frontend/tgt/scsi.go
- integration/core/test_cli.py
- integration/data/common.py
- integration/data/test_backup.py
- scripts/integration-test
- util/util.go
We need to additional handling in tgt frontend in order to swap `_` with `:`,
because `_` isn't allowed in the iSCSI name.
Also update test cases to include all valid name.
As well as add check for volume name and limit the length of volume name to 64
bytes.
> Allow volume with underscore in name

- app/snapshot.go
- integration/core/test_cli.py
- integration/core/test_replica.py
- integration/data/cmd.py
- integration/data/common.py
- integration/data/snapshot_tree.py
- integration/data/test_ha.py
- integration/data/test_snapshot.py
- replica/client/client.go
- replica/replica.go
- replica/replica_test.go
- replica/rest/model.go
- replica/rest/replica.go
- replica/rest/router.go
- replica/server.go
- sync/sync.go
Now remove snapshot will be two steps:
1. When user call `snapshot rm <snapshot_name>`, system will only mark snapshot as `Removed` and won't show it in the chain. But the real file is still intact.
2. When user call `snapshot purge`, system will scan the snapshot tree and
a. Mark any system generated snapshots(e.g. created when rebuilding happens) as `Removed`
b. Remove any `Removed` snapshot from hard drive if possible.
We still unable to remove snapshot in following scenarios:
1. It has multiple children snapshots.
2. It's the parent of volume head disk(live disk).
In the scenario we cannot remove the requested snapshot, we will keep them on the hard drive and retry next time when `snapshot purge` called again.
The reason we've separate the steps are because removing a snapshot can be …
> New snapshot removal mechanism

- frontend/rest/model.go
- replica/rest/model.go
int64 in json must be marked as ",string" in order to be parsed correctly
https://github.com/rancher/longhorn/issues/68
Also found out that it's no longer an issue in Go 1.8.3, but still.
> replica: Fix string to int64 convertion in json

- package/Dockerfile
- package/engine-launcher
It will be used for bootstrap longhorn-engine-launcher, for tgt-blockdev and
tgt-iscsi.
> package: Add engine-launcher

- app/backup.go
- replica/client/client.go
- sync/agent/model.go
- sync/agent/process.go
- sync/backup.go
- types/types.go
- util/util.go
To support S3 backup in longhorn-engine, we need to add aws credential parameters.
- Add aws credential parameter for backup command.
- Add validate s3 command for credential validation.
> Enable S3 support

- Dockerfile.dapper
This commit update the url of golint to be installed while running
make.
Ref: https://stackoverflow.com/questions/52784861/cannot-install-golint-package-wrong-import-path
Signed-off-by: Utkarsh Mani Tripathi <utkarsh.tripathi@mayadata.io>
> fix(golint): update go get url of golint

- Dockerfile.dapper
- backend/remote/remote.go
- frontend/rest/model.go
- integration/core/test_cli.py
- integration/core/test_replica.py
- integration/data/common.py
- integration/data/test_ha.py
- replica/rest/model.go
This PR fixes the following:
1. Docker has forbidden the older download url so `make` is failing
2. `go get golang.org/x/lint/golint` command fails while running `make` ( Ref: golang/go#28291)
```
error:
golang.org/x/tools/go/internal/gcimporter /go/src/golang.org/x/tools/go/internal/gcimporter/bexport.go:212: obj.IsAlias undefined (type *types.TypeName has no field or method IsAlias)
```
3. errors produced by go vet
4. integration tests
Update the url to download docker and dependencies required to run docker (1).
It also update the go version (1.8.3 to 1.10.3) since its not supported (2).
Fix the issues due to go version change (3) and integration tests (4).
Signed-off-by: Utkarsh Mani Tripathi <utkarshmani1997@gmail.com>
> Upgrade docker version

- sync/sync.go
The volume head is being written in, so real size can be different.
> cli: Fix `Inconsistent snapshot` caused by different volume head sizes

- sync/sync.go
In the end, the real size of a sparse file is implementation depended and not
guarantee to be the minimal possible value. So it cannot be used to check data
integrity.
https://github.com/rancher/longhorn/issues/321
> cli: Fix `Inconsistent snapshot` caused by different sizes

- rpc/client.go
The default error timeout for iscsi is 15 seconds. If the data plane of Longhorn
took too long to decide the replica is error, iscsi level timeout error would be
triggered and the volume may be remounted as read-only. So all the retry must be
done before hitting that time limit.
Reduce retry to 2 times, and retry timeout to 4 seconds. It would take (2 + 1) * 4
= 12 seconds before engine declare the replica is error.
See `node.session.err_timeo.abort_timeout` in /etc/iscsi/iscsi.d for the error
timeout setting for iscsi initiator.
Fixs https://github.com/rancher/longhorn/issues/380
> rpc: Reduce timeout for read/write to avoid block layer error

- Dockerfile.dapper
- frontend/tcmu/frontend.go
- frontend/tgt/frontend.go
- integration/data/test_basic_ops.py
If the previous run failed to cleanup the device, it shouldn't become a
show stopper.
https://github.com/rancher/longhorn/issues/401
> frontend: cleanup existing block device by default

- replica/replica.go
- replica/revision_counter.go
https://github.com/rancher/longhorn/issues/412
The current code ignored temporarily replica object's `readonly`
properity, result in rewriting the volume metadata file by mistake
while create backup.
But the volume would normally restored to correct situation because
replica.Close() call would write the correct replica info in memory to
the disk. That's why normally this issue won't be exposed. But in the
case of one replica wasn't closed properly, the corrupted volume
metadata would be shown upon restart, result in snapshot failure etc in
the future.
The step to recover the data would be provided in the issue above.
> Fix creating backup would temporarily change the volume meta head

- frontend/tcmu/frontend.go
- frontend/tgt/frontend.go
- util/util.go
Earlier the device nodes were getting created with 0600 permissions. However, non longhorn block devices had 0660 permission assigned to them.
The following code changes modify the permission from 0600 to 0660. However, unix.Mknod was creating a block device with 0640 instead of 0660.
This could be perhaps due to umask being set to 0022. Hence, we're using os.Chmod to forcefully change the file permissions to 0660.
> Setting the right privileges for block devices

- controller/control.go
Make sure the data in the filesystem cache has been flushed.
This has a potentially problem is `sync` blocked for any reason. It can
be blocked due to failed to flush the cache for other block devices.
Currently we cannot separate them out.
https://github.com/rancher/longhorn/issues/507
> controller: perform sync before snapshot

- .drone.yml
- Publish Longhorn engine image to dockerhub when push event happens to master branch
- Image will be published with tag (master)
> Configure drone to publish to docker hub

- .drone.yml
Reverts rancher/longhorn-engine#360
It broke the drone.
> Revert "Configure drone to publish to docker hub"

- Dockerfile.dapper
- app/replica.go
- backend/remote/remote.go
- frontend/tgt/frontend.go
- integration/launcher/cmd.py
- integration/launcher/test_launcher_basic.py
- integration/setup.py
- integration/tox.ini
- scripts/ci
- scripts/integration-test
- util/util.go
- vendor.conf
- vendor/github.com/longhorn/go-iscsi-helper/iscsiblk/iscsi.go
- vendor/github.com/longhorn/go-iscsi-helper/trash.conf
- vendor/github.com/longhorn/go-iscsi-helper/vendor.conf
Need to use with `longhorn-engine-launcher` `processlauncher` branch.
So far:
1. Disabled all the existing integration tests.
2. Add a few integration test for process launcher.
To do:
1. Complete the processlauncher in `longhorn-engine-launcher` for multiple engine shared tgt, upgrade and enable/disable frontend.
2. Add process launcher test cases with data in the longhorn-engine.
> Process Launcher initial work

- util/util.go
- util/util_test.go
- util/validation.go
This PR modifies the logic used to validate labels on `Snapshots` and `Backups` in `longhorn-engine`.
Instead of treating them as `Labels` using our own custom rules, the only requirement for the `Labels` is that the keys follow `Qualified Name` specifications that are defined by `Kubernetes` (which they use for their own logic for handling `Labels` and `Annotations`). This effectively allows the user to use any value they wish for the value of the `Label` similar to a `Kubernetes Annotation`, provided that the value is not `empty`.
This PR is a part of the implementation of longhorn/longhorn#563 as it'll open up the ability to store other data types such as `JSON` in the `Snapshot Labels` and `Backup Labels`.
> Validate Snapshot Labels as Kubernetes Annotations

- controller/revert.go
- integration/core/test_cli.py
- integration/data/common.py
- integration/data/snapshot_tree.py
- integration/data/test_restore_to_file.py
- integration/data/test_snapshot.py
The following changes include two things:
1. Integration test to manually shutdown before snapshot revert operation and start the launcher after snapshot revert completion.
2. Modify the controller logic in revert to check if the frontend is disabled before performing snapshot revert. Otherwise, abort the snapshot revert.
> Frontend shutdown before snapshot revert

- integration/core/test_cli.py
- integration/data/cmd.py
- sync/backup.go
Earlier, the restore status had `restoreError` JSON tag for the attribute RestoreError. Going forward we are changing it to `error` as it's already part of RestoreStatus message.
> Restore Status changing json name for restore error

- backup/main.go
- integration/core/test_cli.py
- integration/data/cmd.py
- replica/backup.go
- sync/backup.go
- sync/rpc/server.go
The following code modifications include renaming `backupError` to
`error`. Further, the replica backup object name
is changed from `Backup` to `BackupStatus` and it's attributes
`BackupProgress` and `BackupError` to `Progress` and `Error`
respectively.
> Renames related to backup

- app/restore_to_file.go
- replica/backup.go
- sync/rpc/server.go
The following code changes removes the timeout logic from the backup restore. This includes removing from the restore_to_file path as well.
Issue: https://github.com/longhorn/longhorn/issues/644
> Remove the timeout logic from Backup Restore

- package/Dockerfile
Make sure the children process are reaped correctly.
https://github.com/longhorn/longhorn/issues/795
> Use `tini` as the entry point for the instance manager

- Dockerfile.dapper
Also workaround https://github.com/longhorn/longhorn/issues/968
> build: Update liblonghorn and tgt

- pkg/instance-manager/engine/engine_manager.go
- pkg/instance-manager/types/types.go
even if the related process is not found or the frontend cleanup fails
https://github.com/longhorn/longhorn/issues/854
https://github.com/longhorn/longhorn/issues/923
> instance manager: Make sure the engine launcher can be cleaned up

- scripts/integration-test
It's 32768 to 60999 by default in Linux.
https://github.com/longhorn/longhorn/issues/1085
> test: Avoid ephemeral port range

- go.mod
- go.sum
- integration/tox.ini
- pkg/sync/rpc/server.go
- pkg/types/types.go
- pkg/util/util.go
- scripts/integration-test
- vendor/github.com/longhorn/backupstore/.gitignore
- vendor/github.com/longhorn/backupstore/deltablock.go
- vendor/github.com/longhorn/backupstore/driver.go
- vendor/github.com/longhorn/backupstore/http/client.go
- vendor/github.com/longhorn/backupstore/s3/s3.go
- vendor/github.com/longhorn/backupstore/s3/s3_service.go
- vendor/github.com/longhorn/backupstore/singlefile.go
- vendor/modules.txt
Depends on longhorn/backupstore#32 and requires an updated go module reference to be able to correctly build this.
This is to address longhorn/longhorn#704
> Add support for custom ssl certificates for S3 backups

- go.mod
- go.sum
- vendor/github.com/longhorn/backupstore/http/client.go
- vendor/modules.txt
This is to fix the ssl certificate check for backups
https://github.com/longhorn/longhorn/issues/704
> Update longhorn/backupstore to v0.0.0-20200513030129-7f9a1e8a1d69

- go.mod
- go.sum
- integration/common/cmd.py
- integration/common/constants.py
- integration/common/util.py
- integration/core/test_cli.py
- integration/data/test_backup.py
- scripts/integration-test
- vendor/github.com/longhorn/backupstore/backupstore.go
- vendor/github.com/longhorn/backupstore/deltablock.go
- vendor/github.com/longhorn/backupstore/driver.go
- vendor/github.com/longhorn/backupstore/fsops/fsops.go
- vendor/github.com/longhorn/backupstore/s3/s3.go
- vendor/github.com/longhorn/backupstore/s3/s3_service.go
- vendor/github.com/longhorn/backupstore/util/util.go
- vendor/modules.txt
Integration tests for the backup delete changes.
We now have a test that verifies the correct gc operation for out of
order deletes and dependent blocks. We also now have a test that makes
sure that blocks are not deleted while there is an in progress backup.
longhorn/longhorn#1431 
longhorn/longhorn#1433 
With the orphaned block deletion in place we can now remove corrupted
backup.cfg files, since that will just orphan the blocks and they will
be cleaned up with all the other orphaned blocks.
With the removal of the volume.cfg existence check we can now also
cleanup a volume folder including all subfolders when requested via a
backup volume removal.
longhorn/longhorn#1213
depends on longhorn/backupstore#41
> Update backupstore for blk fixes

- go.mod
- go.sum
- integration/common/constants.py
- integration/data/test_backup.py
- vendor/github.com/longhorn/backupstore/config.go
- vendor/github.com/longhorn/backupstore/list.go
- vendor/modules.txt
The test makes sure that if there is failure when trying to retrieve the
backup names for that volume, that the list operation does not fail.
Since a failure would block the list operation of returning information
for all the other backup volumes. Instead of failing the whole operation
we add a Error message to the backup volume.
longhorn/longhorn#1410
> Add test for backup volume list

- go.mod
- go.sum
- integration/data/test_backup.py
- vendor/github.com/longhorn/backupstore/config.go
- vendor/github.com/longhorn/backupstore/deltablock.go
- vendor/github.com/longhorn/backupstore/util/util.go
- vendor/modules.txt
We should ignore badly named files instead of erroring, since the files don't match our search pattern we don't need to concern ourselves with them (we filter them out)
depends on longhorn/backupstore#42
longhorn/longhorn#1410
> Backup list operation should ignore badly named files

- app/cmd/backup.go
- go.mod
- go.sum
- integration/data/test_restore_inc.py
- pkg/backup/main.go
- pkg/replica/backup.go
- pkg/sync/backup.go
- pkg/sync/rpc/server.go
- pkg/sync/sync.go
- vendor/github.com/longhorn/backupstore/deltablock.go
- vendor/modules.txt
https://github.com/longhorn/longhorn/issues/1188
Summary:
1. Refactor the implementation of restore:
1. Check the parameters.
2. Prepare to restore: Initiate the restore status and set the fields. Then all restore errors after the preparation will be recorded in the restore status.
3. Start to restore: prepare the restore file and start to fetch inf/data from the backupstore.
4. Finish restore: wait for the restore complete, reload/revert the snapshot, use a defer function to update the restore status and the fields.
2. Format the restore errors for replica syne agent servers and return 
3. Update the integration test: Test the error during the starting stage will be recorded in the restore status; check the error from sync agent servers are formated and printed.
> Restore Rafactoring

- go.mod
- go.sum
- vendor/github.com/longhorn/backupstore/nfs/nfs.go
- vendor/modules.txt
This PR updates the `backupstore` dependency to `2458fbe`, which contains the fix for longhorn/longhorn#1488 and prevents NFS mounts from potentially falling back to NFSv3.
> Update backupstore to 2458fbe

- go.mod
- go.sum
- integration/data/test_backup.py
- vendor/github.com/longhorn/backupstore/deltablock.go
- vendor/modules.txt
Update backupstore to v0.0.0-20200709195833-7392333d6d22 for fixing the
LastBackup fields in volume.cfg when deleting the latest backup
https://github.com/longhorn/longhorn/issues/1381
> Update backupstore to v0.0.0-20200709195833-7392333d6d22

- pkg/sync/rpc/server.go
This fix is needed for users who are running a cluster behind a http_proxy and wish to use AWS S3 as the backupstore.
We set the environment variables before doing `BackupRestoreIncrementally` or `BackupRestore` so that Engine can use the http proxy and go out when doing backup restore.
longhorn/longhorn#1540
>  pkg/sync/rpc: set evirontment variables HTTP_PROXY, HTTPS_PROXY, and NO_PROXY so that engine use the http proxy when doing backup restore.

- integration/common/core.py
- integration/data/test_ha.py
- pkg/replica/replica.go
- pkg/replica/server.go
This fix adds the replica to report self detected errors through ping
response. And this will trigger replica rebuild automatically.
https://github.com/longhorn/longhorn/issues/1615
> replica: Fix when replica crashed or removed triggers replica rebuild

- .drone.yml
- README.md
This reverts commit 2105a1fb81fd637a2d638eb33165d94e5b13d16d.
drone-publish.longhorn.io has been fixed.
> Revert "Update to use Rancher drone"

- integration/data/test_restore.py
- pkg/replica/backup.go
- pkg/sync/rpc/server.go
After the discussion with @joshimoo, we need to avoid recording the errors before performing the actual restore. Otherwise, the related replica will be marked as ERROR once there is a restore file locking timeout, which is bad for the user experience.
> Avoid recording the pre-restore errors in syncagent server restore info

- pkg/replica/backup.go
Since the similar logic already implemented in `rb.assertOpen` above, this seems safe to remove.
> Remove duplicated check for opened snapshot/volume

- pkg/replica/server.go
Seems to make more sense when source and target are swapped in place.
> Swap source and target around in the message

- pkg/sync/rpc/server.go
> Use defer for RWMutex Unlock

- integration/common/core.py
- integration/instance/test_launcher_basic.py
Test case for engine and replica revision counter setting mismatch.
Case 1: engine has revision counter enabled, one replica is revision
counter enabled, the other one is disabled.
Case 2: engine has revision counter disabled, one replica is revision
counter disabled, the other one is enabled.
https://github.com/longhorn/longhorn/issues/1840
> Add engine integration test for engine revision counter mismatch case

- go.mod
- go.sum
- pkg/backup/main.go
- vendor/github.com/longhorn/backupstore/backupstore.go
- vendor/github.com/longhorn/backupstore/deltablock.go
- vendor/github.com/longhorn/backupstore/list.go
- vendor/modules.txt
- Pass labels to backup volume structure
- Bump longhorn/backupstore version to add KubernetesStatus metadata to volume.cfg
https://github.com/longhorn/longhorn/issues/1539
> Bump longhorn/backupstore version to add KubernetesStatus metadata to volume.cfg

- go.mod
- go.sum
- vendor/github.com/longhorn/backupstore/nfs/nfs.go
- vendor/modules.txt
add nfs server mount directory log to resolve ticket '[Question] unable to mount NFS backup' (#2242)
- Add error to log message make directory failed
Enhancement
Refs: https://github.com/longhorn/longhorn/issues/2242
Need to wait for PR https://github.com/longhorn/backupstore/pull/65 merge and update go.mod, go.sum, and module.txt
Signed-off-by: Clark Hsu <clark.hsu@suse.com>
> add nfs server mount directory log (#2242)

- go.mod
- go.sum
- integration/data/test_snapshot.py
- pkg/controller/control.go
- vendor/github.com/longhorn/go-iscsi-helper/util/util.go
- vendor/modules.txt
We evaluate whether the fs is mounted by running `findmnt /dev/longhorn/<volume_name>` in the host mount namespace.
Since if the volume is used, the engine will be on the same node as the workload
that is using it and the volume will be mounted by kubelet in the host mount namespace.
In the case where the volume is not mounted we fall back to a system level sync.
I added an integration test, that mounts the device in the host mount namespace and writes some file onto it. Then does snapshots & restores.
I need to mount&umount the device after the restore, since the test will shutdown the frontend. This is equivalent to our killing of the workload pods, to get the volume to remount.
longhorn/longhorn#2187
depends on an update of the go-iscsi-helper dependency which is included
as a dev …
> Freeze a volumes filesystem if mounted before taking a snapshot

- pkg/backend/remote/remote.go
- pkg/controller/control.go
- pkg/replica/replica.go
add logs for debugging snapshot to resolve ticket '[FEATURE]Add more debug logs for snapshotting' (#2161)
- add snapshot time
- add sendfile time
- enhancement
Additional log like following
2021-03-04T04:10:53.970318517Z time="2021-03-04T04:10:53Z" level=info msg="Finish snapshot for tcp://10.42.1.12:10000: 075a33e7-343b-4cad-b0c6-ff9c19016ec5 and take 2.63582ms"
2021-03-04T04:10:53.970318517Z time="2021-03-04T04:10:53Z" level=info msg="Finish sending file /tmp/test256KB.tmp and take 1.644776033s"
Refs: # https://github.com/longhorn/longhorn/issues/2161
Wait for https://github.com/longhorn/sparse-tools/pull/71 to update go.mod, go.sum, and module.txt
Signed-off-by: Clark Hsu <clark.hsu@suse.com>
> add logs for debugging snapshot (#2161)

- go.mod
- go.sum
- pkg/sync/rpc/server.go
- pkg/util/util.go
- vendor/github.com/longhorn/backupstore/s3/s3_service.go
- vendor/modules.txt
- Allowed AWS credential to be empty (it will check at longhorn-manager) in order to support AWS IAM Role
- Bump longhorn/backupstore version
https://github.com/longhorn/longhorn/issues/1526
> Support AWS IAM Role

- go.mod
- go.sum
- pkg/sync/rpc/server.go
- vendor/github.com/longhorn/sparse-tools/cli/ssync/main.go
- vendor/github.com/longhorn/sparse-tools/sparse/client.go
- vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go
- vendor/modules.txt
add command line argument directio to resolve ticket '[BUG] sparse-tools: ssync should explicitly asking for directIO or not, rather than determine is using filesize' (#1943)
1. Update to use `directIO` from the https://github.com/longhorn/sparse-tools/pull/69
1. Update to use `directIO` from the https://github.com/longhorn/sparse-tools/pull/70
Bug fixing.
Updated/Added unit test cases, and integration test should pass
Build log should have log like following:
```
> grep -rnis directio ./logs_longhorn_longhorn-engine_1_3.log 
81:time="2021-03-22T07:56:54Z" level=info msg="source file size: 178, setting up directIO: false"
82:[test-0faf0f23-replica-1-2] time="2021-03-22T07:56:54Z" level=info msg="open: receiving fileSize: 178, setting up directIO: false"
87:time="2021-03-22T07:56:54Z" …
```
> add command line argument directio (#1943)

- pkg/replica/server.go
The user uses longhorn-engine version v1.0.2, and the log fulls with
```shell
time="2021-01-22T02:36:05Z" level=warning msg="pvc-24e08e51-3db8-45b4-8860-4f1adcccd9c7-e-bc240ffa: time="2021-01-22T02:35:51Z" level=info msg="Starting with replicas [\"tcp://10.42.0.254:10000\"]""
time="2021-01-22T02:36:05Z" level=warning msg="pvc-24e08e51-3db8-45b4-8860-4f1adcccd9c7-e-bc240ffa: time="2021-01-22T02:35:51Z" level=info msg="Connecting to remote: 10.42.0.254:10000""
time="2021-01-22T02:36:05Z" level=warning msg="pvc-24e08e51-3db8-45b4-8860-4f1adcccd9c7-e-bc240ffa: time="2021-01-22T02:35:51Z" level=warning msg="failed to create backend with address tcp://10.42.0.254:10000: Replica must be closed, Can not add in state: error""
time="2021-01-22T02:36:05Z" level=warning …
```
> Add error log when read volume.meta failed

- go.mod
- go.sum
- vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go
- vendor/modules.txt
Bump version to includes https://github.com/longhorn/go-iscsi-helper/pull/39
Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>
> Bump longhorn/go-iscsi-helper version to fix typo

- go.mod
- go.sum
- vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go
- vendor/github.com/longhorn/sparse-tools/sparse/client.go
- vendor/github.com/longhorn/sparse-tools/sparse/file.go
- vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go
- vendor/github.com/longhorn/sparse-tools/sparse/sfold.go
- vendor/github.com/longhorn/sparse-tools/sparse/util.go
- vendor/modules.txt
Backport sparse-tools update for iterative sync/fold
This also has a typo fix for the go-iscsi-helper dependency this is already
in master, since it doesn't have a semantic change I included it as well.
longhorn/longhorn#1948
longhorn/longhorn#2507
longhorn/longhorn#2640
> Backport replica rebuild enhancement

- Dockerfile.dapper
- pkg/backend/remote/remote.go
- pkg/dataconn/client.go
This changes the timeout logic in dataconn.Conn.  Previously the timeout occurred when a response operation was not received for eight seconds (with one retry).   When multiple operations were being performed simultaneously on a slow disk, this timeout was likely to occur.  However, when multiple operations were being performed simultaneously, the replica is regularly sending responses to those operations.  So, this change makes the timeout occur when no response to any of the pending read or write operation has been received for eight seconds. 
This will allow slow disks to not timeout because the replica will be completing and sending the responses to operation regularly.   This addresses slow disks failing as part of #2206 but doesn't fixed the performance issue will spinning disks in …
> Timeout replica when no I/O responses are received

- pkg/controller/replicator.go
The monitoring goroutine was continuing to run after the replica was
removed.  This caused a problem when a replica is recreated for the same
IP address and port after one is deleted.  When a replica is removed,
the channel that the monitoring goroutine is waiting for will eventually
get an error message.  In the normal case, the SetReplicaMode won't find
a replica with the address to mark as ERR.  However, when another
replica is with the same address is added after the original was
removed, SetReplicaMode for the old monitorChan will mark the new
replica as ERR with SetReplicaMode.
This change makes removing the replica also stop the monitoring
goroutine that was launched for that replica.  It puts a nil error on
the replica's monitor channel so monitoring goroutine  will exit as part …
> Stop monitoring goroutine when removing replica

- pkg/controller/replicator.go
The replica monitor channel goroutine is still running when a
controller's volume is shutdown via the GRPC VolumeShutdown method.
This change makes stops the Controller's replica monitor goroutine when
the volume is shutdown.
https://github.com/longhorn/longhorn/issues/1628
> Make closing all the replicas stop all the replica monitors

- Dockerfile.dapper
- package/Dockerfile
ref: https://github.com/longhorn/longhorn/issues/2796
note: This will be backported to v1.1.3.
> Add instance manager cli back to engine image

- app/cmd/add_replica.go
- app/cmd/backup.go
- app/cmd/controller.go
- app/cmd/ls_replica.go
- app/cmd/rm_replica.go
- app/cmd/snapshot.go
- app/cmd/stats.go
- app/cmd/sync_agent.go
- app/cmd/volume.go
- pkg/controller/client/controller_client.go
- pkg/controller/rebuild.go
- pkg/controller/revert.go
- pkg/replica/client/client.go
- pkg/sync/backup.go
- pkg/sync/rpc/server.go
- pkg/sync/sync.go
- version.go
This enables GRPC connection reuse for the Controller/Replica clients
We also initialize the clients as part of the Constructors to deal with incorrect addresses for the example
I retained the prior behavior of the background lazy connection, so connection establishment errors would still
be reported as part of the first grpc call.
With this code structure we have the ability to add retry loops for transient errors, i.e. subconnection in failures.
I will create an EPIC for grpc communication improvemets so we can track this further.
I only implement the Task change for  the BackupStatus retrieval, the others can be just as easily implemented after this PR.
We should consider the Task struct as deprecated and over time turn the instance methods into free functions.
Then the caller can pass …
> 2818-bulk-backup-status-retrieval

- integration/core/test_cli.py
- pkg/controller/replicator.go
https://github.com/longhorn/longhorn/issues/1628
> 1628 backport closing monitoring channel

- app/cmd/backup.go
- pkg/replica/client/client.go
- pkg/util/once.go
- pkg/util/once_test.go
Lazily initialize the replica clients for replica/sync service
This is to optimize the connection count for the longhorn-manager engine
monitor loop, in a single loop the monitor executes the engine binary 8
times this leads to a total connection count of `f() = 8e + 6 * 2r = 20`
for a volume with 1 replica.
Since all the calls the monitor makes only require either the replica or
the sync client, we can reduce this further with this optimization to
`g() = 8e + 6r = 14` per monitor loop.
The monitor loop executes `60/5 = 12` times per minute, so our total 
connections per minute are reduced from **240** to **168**. For volume with 3 
replicas we end up with **312** connection per minute.
No further optimization on this end is possible, the next required task
is removal of the direct engine …
> 2818 further socket usage optimizations

- go.mod
- go.sum
- vendor/github.com/longhorn/backupstore/go.mod
- vendor/github.com/longhorn/backupstore/go.sum
- vendor/modules.txt
Downupgrade spf13/afero to v1.5.1 to prevent using
testing/fstest which is only available at Go 1.16+
Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>
> Bump longhorn/backupstore version

- pkg/sync/rpc/server.go
This adds new snapshots marked to be removed while performing the purge
to the total number of snapshots to purge so that the percentage does
not exceed 100%.
https://github.com/longhorn/longhorn/issues/2892
> Fix purge status percentage

- pkg/controller/control.go
there is a race condition around the fsfreeze between mount point evaluation of a device and the invocation of the fsfreeze if the device is unmounted from that mount point, the folder will now reference the original device that hosts the mount point folder.
As a hotfix I am removing the fsfreeze invocation and replacing it with our previous behavior of calling sync.
As a result of this change, the volume head is no longer dirty after
a snapshot operation unless there was additional io, so we are again
skipping recurring backups if no new io is present.
REF: longhorn/longhorn#2555
ISSUE: longhorn/longhorn#3125
> Replace fsfreeze with prior behavior of system sync due to race condition

- go.mod
- go.sum
- vendor/github.com/longhorn/backupstore/nfs/nfs.go
- vendor/modules.txt
This PR is related to backupstore.
(1) Only return coalesce error when last NFSv4 version fails to mount.
(2) Remove NFSv3 try mount and umount from defer function.
> nfs: only return coalesce error when last NFSv4 version fails to mount

- pkg/controller/rebuild.go
Prevent longhorn-engine from crashing because it attempts to access the first element in an array whose length is zero.
https://github.com/longhorn/longhorn/issues/3822
> Check that array isn't empty before accessing

- pkg/replica/replica.go
Since we forgot to remove the snapshot from the r.diskChildrenMap when removing the snapshot, when the user creates snapshot with the same name again, the children map of the snapshot is messed up
longhorn/longhorn#3883
> Fix bug forget to remove the snapshot from r.diskChildrenMap when removing snapshot

- pkg/replica/replica.go
longhorn/longhorn#3883
longhorn/longhorn#3912
> [Backport v1.1.4] Fix bug forget to remove the snapshot from r.diskChildrenMap when removing snapshot

- pkg/replica/replica.go
longhorn/longhorn#3883
longhorn/longhorn#3911
> [Backport v1.2.5] Fix bug forget to remove the snapshot from r.diskChildrenMap when removing snapshot

- pkg/dataconn/wire.go
Writing or reading a header of a request calls multiple writes and reads, which increase the latency of the data io.
The task is to reduce the number of the calls, memory allocations and memory copies.
[Longhorn 4122](https://github.com/longhorn/longhorn/issues/4122)
> Reduce write and read calls while reading and writing requests

- pkg/dataconn/wire.go
Writing or reading a header of a request calls multiple writes and reads
which increase the latency of the data io because the memory allocations
and data copy.
https://github.com/longhorn/longhorn/issues/4122
https://github.com/longhorn/longhorn/issues/4169
> Reduce write and read calls while processing requests

- pkg/controller/control.go
- pkg/replica/replica.go
Creating a snapshot with a same ID (name) will lead to the volume
corruption. The fix is rejecting the snapshot creation requst if
the snapshot is already existing.
[Longhorn 4250](https://github.com/longhorn/longhorn/issues/4250)
> Reject snapshot creation request if the snapshot is already existing

- pkg/controller/control.go
If longhorn use the setting of storage-network, and the second
network is contronllerd by ovs-cni, there is three
instance-managers of replica, and the instance-manager of replica
may have the same storage ip address.
longhorn/longhorn#4281
Signed-off-by: 王一知 <wangyizhi@inspur.com>
> Duplicated IP address of sotrage-network

- pkg/controller/control.go
If longhorn use the setting of storage-network, and the second
network is contronllerd by ovs-cni, there is three
instance-managers of replica, and the instance-manager of replica
may have the same storage ip address.
longhorn/longhorn#4282
Signed-off-by: 王一知 <wangyizhi@inspur.com>
> add format duplicate address

- pkg/backend/file/file.go
- pkg/backend/remote/remote.go
- pkg/controller/control.go
- pkg/dataconn/client.go
- pkg/sync/sync.go
- pkg/types/types.go
If there is any available replica, mark the replicas ERR if their volume.meta are in invalid state.
https://github.com/longhorn/longhorn/issues/4212
> Mark the replica ERR if its volume.meta is in invalid state

- pkg/controller/control.go
> [BACKPORT][v1.2.6] Fix data corruption due to COW and block size not being aligned during rebuilding replicas

- app/cmd/replica.go
- pkg/backingfile/backingfile.go
- pkg/replica/replica.go
- pkg/replica/server.go
- pkg/util/util.go
https://github.com/longhorn/longhorn/issues/4599
https://github.com/longhorn/longhorn/issues/4635
(cherry picked from commit 1d5d3c94c572651c546d29dc074c2a4608adc283)
> [BACKPORT][v1.3.2] Reorganize volume, replica and backing image sector sizes

- app/cmd/restore_to_file.go
New version of qemu-img requires `-F` flag for backing file format when we upgrade the base image version SLES from 15.3 to 15.4
https://gitlab.com/qemu-project/qemu/-/commit/497a30dbb065937d67f6c43af6dd78492e1d6f6d
longhorn/longhorn#4632
Signed-off-by: James Lu <james.lu@suse.com>
> fix(qemu-img): Require -F with -b backing image

- app/cmd/restore_to_file.go
New version of qemu-img requires `-F` flag for backing file format when we upgrade the base image version SLES from 15.3 to 15.4
longhorn/longhorn#4716
Signed-off-by: James Lu <james.lu@suse.com>
> [BACKPORT][v1.2.6] fix(qemu-img): Require -F with -b backing image

- app/cmd/restore_to_file.go
New version of qemu-img requires `-F` flag for backing file format when we upgrade the base image version SLES from 15.3 to 15.4
longhorn/longhorn#4717
Signed-off-by: James Lu <james.lu@suse.com>
> [BACKPORT][v1.3.3] fix(qemu-img): Require -F with -b backing image

- app/cmd/backup.go
- app/cmd/controller.go
- app/cmd/restore_to_file.go
- app/cmd/snapshot.go
- app/cmd/sync_agent.go
- app/cmd/volume.go
- integration/core/test_replica.py
- main.go
- pkg/backend/remote/remote.go
- pkg/backup/main.go
- pkg/controller/client/controller_client.go
- pkg/controller/control.go
- pkg/controller/rebuild.go
- pkg/controller/util.go
- pkg/frontend/rest/frontend.go
- pkg/frontend/rest/server.go
- pkg/frontend/socket/frontend.go
- pkg/qcow/libqcow.go
- pkg/replica/backup.go
- pkg/replica/client/client.go
- pkg/replica/diff_disk.go
- pkg/replica/replica.go
- pkg/replica/revision_counter.go
- pkg/replica/rpc/server.go
- pkg/replica/server.go
- pkg/sync/backup.go
- pkg/sync/rpc/server.go
- pkg/sync/sync.go
Error strings should not be capitalized unless beginning with proper nouns or acronyms.
[Longhorn 4828](https://github.com/longhorn/longhorn/issues/4828)
> Unify the format of returned error messages

- pkg/controller/control.go
- pkg/controller/replicator.go
Replica banckend needs to be closed if the number of sanpshots is up to the limitation and replica rebuding is occurred.
longhorn/longhorn#3828
> Replica must be closed when rebuilding failed with `too many snapshots created`

- scripts/build
~Implements suggestion in https://github.com/longhorn/longhorn/issues/4415#issuecomment-1214885963 and disable CGO here too like it was done in longhorn-manager by https://github.com/longhorn/longhorn-manager/pull/61~
Looks that longhorn-engine needs CGO so switched to alternative solution proposed in https://github.com/longhorn/longhorn/issues/1768#issuecomment-690778513
> Tagging netgo to be used while compiling with cgo 

- pkg/replica/replica.go
- pkg/replica/server.go
Volume will be stuck in attaching and detaching loop when attaching a volume with volume metafile deleted or empty.
Try to rebuild the volume metafile when attaching a volume.
longhorn/longhorn#4846
Regression test result: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2601
Run a new Regression test: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2628/
> fix(replica): volume metafile deleted or empty

- pkg/replica/replica.go
- pkg/replica/server.go
- pkg/types/types.go
Volume will be stuck in attaching and detaching loop when attaching a volume with volume metafile deleted or empty.
Try to rebuild the volume metafile when attaching a volume.
longhorn/longhorn#4846
https://github.com/longhorn/longhorn/issues/4983
> [BACKPORT][v1.2.7] fix(replica): volume metafile deleted or empty

- pkg/replica/replica.go
- pkg/replica/server.go
- pkg/types/types.go
Volume will be stuck in attaching and detaching loop when attaching a volume with volume metafile deleted or empty.
Try to rebuild the volume metafile when attaching a volume.
longhorn/longhorn#4846
https://github.com/longhorn/longhorn/issues/4847
> [BACKPORT][v1.3.3] fix(replica): volume metafile deleted or empty

- app/cmd/controller.go
- pkg/backend/remote/remote.go
- pkg/controller/init_frontend.go
- pkg/replica/server.go
> Set default engine-replica-timeout vaule for engine controller start command

- pkg/controller/control.go
- pkg/controller/replicator.go
Replica banckend needs to be closed if the number of snapshots is up to the limitation and replica rebuiding is occurred.
Ref: longhorn/longhorn#3828, https://github.com/longhorn/longhorn/issues/5116
> [BACKPORT][v1.3.3] fix(replica): Replica must be closed when rebuild

- pkg/replica/replica.go
Longhorn/longhorn#5129
Also, the fix make the trim operation supports volumes with backing images. (Longhorn/longhorn#5128)
> Don't mark the backing image as removed

- pkg/meta/version.go
Update CLIAPIVersion to 8 because of the newly introduced compression enhancement.
Longhorn/longhorn#5376
> meta: update CLIAPIVersion to 8

- pkg/sync/backup.go
InspectBackup fail if the volume or backup is missing. Set taskErr for failing the volume restoration.
Longhorn/longhorn#5458
> RestoreBackup: set taskErr if failed to inspect backup

- app/cmd/controller.go
- pkg/controller/control.go
- pkg/controller/errors.go
When an engine had no available backend, the controller emitted a message stating "...no available backend...". Afterward, the volume controller blindly marked all replicas as failed.
To create a RWX volume, it was first created on node A, and then the sharemanager resource was created with node A as the owner. The sharemanager controller then created a sharemanager pod, which might be located on node B. After the pod was created, the sharemanager resource's owner was transferred to node B, causing the volume to detach from node A and attach to node B.
However, if replicas were deleted because of detachment, the in-progress engine instance's startup would fail due to the "...no available backend..." error. This caused all replicas to be marked as failed (healthyAt is empty and failedAt is …
> Separate service unavailable and replica error

- go.mod
- go.sum
- vendor/github.com/longhorn/sparse-tools/sparse/rest/server.go
- vendor/modules.txt
Issue: https://github.com/longhorn/longhorn/issues/4305
Depends on: https://github.com/longhorn/sparse-tools/pull/93
Currently, it is not possible to backport vendor update from the master-head to v1.4.x
So we have to create the branch from v1.4.x and create the PR to prevent conflicts.
> [v1.4.x] vendor: update sparse-tool

- pkg/sync/rpc/list.go
This is the same as the previous PR #924.  I made the mistake of renaming the branch, which closed that one.
[BUG] Longhorn Instance Manager Memory leak #6481
Three changes:
Put in a log to catch runaway growth.
Ensure only one list entry per customer (backup ID).
Do the prune logic for "error" as well as "completed" status.
> Fix 6481 - unbounded growth in BackupList from failure retries.

- .drone.yml
- scripts/ci-without-it
https://drone-publish.longhorn.io/longhorn/longhorn-engine/718/1/3
`iscsiadm` not found from the s390x runner. After fixing this, the integration testing will be re-enabled in s390x pipeline. 
```
E           grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
E           	status = StatusCode.UNKNOWN
E           	details = "failed to init frontend: device test-a11a5832-volume: failed to stop iSCSI device: failed to logout target: failed to execute: nsenter [--mount=/host/proc/263111/ns/mnt --net=/host/proc/263111/ns/net iscsiadm --version], output , stderr nsenter: failed to execute iscsiadm: No such file or directory
```
> ci: pause integration testing for s390x

- .drone.yml
Enabling ci with `it` for s390x
Reverting https://github.com/longhorn/longhorn-engine/pull/942 after fixing the issue https://github.com/longhorn/longhorn/issues/6891
> Renable CI IT for s390x

- Dockerfile.dapper
- scripts/ci
- scripts/ci-without-it
- scripts/generate-grpc
related to: https://github.com/longhorn/longhorn/issues/6973
Example for the usage.
```
$ make generate-rpc
... some build logs
integration/rpc/controller/controller_pb2.py | 200 ++++++++++---- integration/rpc/controller/controller_pb2_grpc.py | 17 ++ integration/rpc/replica/re
plica_pb2.py | 114 +++++++- integration/rpc/replica/replica_pb2_grpc.py | 17 ++ proto/ptypes/controller.pb.go | 317 ++++++++++++++++------ proto/ptype
s/replica.pb.go | 307 +++++++++++++++------
Please update GRPC generated code.
$ git status
On branch tmp-gen-rpc
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   integration/rpc/controller/controller_pb2.py
modified: …
```
> build: improve the gPRC generator script

- pkg/backend/remote/remote.go
- pkg/controller/client/controller_client.go
- pkg/replica/client/client.go
- pkg/sync/rpc/server.go
This reverts commit https://github.com/longhorn/longhorn-engine/commit/636a99aad3ba51dd44693a72da5b2d2353734399 for the reason same as https://github.com/longhorn/longhorn-engine/pull/973#issuecomment-1864078004.
https://github.com/longhorn/longhorn/issues/7364
> Revert "refactor: replace deprecated grpc.WithInsecure"

- pkg/replica/diff_disk.go
- pkg/replica/replica_test.go
ref: https://github.com/longhorn/longhorn/issues/6899
I think we should still return `len(read sectors)` when reading out of the boundary (expansion part of the specific image)
The reason is that, from the caller's perspective, it is reading from the `"Volume"`
```
func (r *Replica) ReadAt(buf []byte, offset int64) (int, error) {
r.RLock()
c, err := r.volume.ReadAt(buf, offset) // which will call diffDisk.fullReadAt()
r.RUnlock()
return c, err
}
```
So it has no knowledge about the snapshot chain underneath.
If it reads outside of the boundary of the `"Volume"`, we do return `io.ErrUnexpectedEOF` error [here](https://github.com/longhorn/longhorn-engine/blob/master/pkg/replica/diff_disk.go#L235)
But if it only reads outside of the boundary of `"specific snapshot image"`, and we allow it to …
> fix: return the read sectors length when it reads the expansion part

- .drone.yml
N/A
Run integration-tests only when the GitHub event is PR.
>  ci: run integration-test only if gh event is PR

- pkg/controller/control.go
Longhorn 7103
longhorn/longhorn#7103
Don't return an error to tgt/liblonghorn when UNMAP is called during a rebuild. We are not required to do so, and doing so causes https://github.com/harvester/harvester/issues/4739.
> Don't return an error on unmap while rebuilding

- .github/workflows/codespell.yml
- README.md
- pkg/controller/control.go
- pkg/qcow/libqcow.go
> fix: codespell

- app/cmd/restore_to_file.go
- pkg/util/util.go
Issue #
Missing one parameter of Set function for gopkg.in/cheggaaa/pb when updating the package gopkg.in/cheggaaa/pb.v2 to v2.0.7.
> fix: missing one parameter of Set function for gopkg.in/cheggaaa/pb

- Dockerfile.dapper
- integration/instance/test_launcher_basic.py
ref: https://github.com/longhorn/longhorn/issues/8094
0. We are now checking out latest instance-manager when buiding instance-manager inside longhorn-engine [here](https://github.com/ChanYiLin/longhorn-engine/commit/563531ded3ed38dc6d5bc05fc7f1729645d31fc4)
1. When users manually exec longhorn-instance-manager inside longhorn-engine image, they will encounter
```
longhorn-instance-manager: error while loading shared libraries: libqcow.so.1: cannot open shared object file: No such file or directory
```
2. Fixed it by adding ldflags so  the binary can find the lib
3. Since we validate engine binary path [here](https://github.com/longhorn/longhorn-instance-manager/blob/master/pkg/process/process_manager.go#L192), we have to soft link the binary inside the container to the tmp path, so the …
> fix(instance-maanger): add ldflags when building instance manager

- pkg/dataconn/wire.go
Issue #
When the error is triggered, the log should print out the wrong `msg.MagicVersion` rather than its address
> dataconn: Fix error log

- pkg/replica/diff_disk.go
- pkg/replica/replica_test.go
Issue: https://github.com/longhorn/longhorn/issues/8235
Prevent the unmap length of a negative number
Also, add unittest for unmap operations
> Prevent the unmap length of a negative number

- pkg/backend/remote/remote.go
- pkg/dataconn/client.go
- pkg/replica/revision_counter.go
1. Improve revision counter logic
2. Increase the connection from engine to replica
Please see the improvement test result in the issue description at longhorn/longhorn#8436
longhorn/longhorn#8436
TODO:
> Fix some v1 data path bottlenecks

- app/cmd/controller.go
- app/cmd/restore_to_file.go
- main.go
- pkg/controller/control.go
- pkg/dataconn/client.go
- pkg/dataconn/server.go
- pkg/frontend/rest/frontend.go
- pkg/frontend/socket/frontend.go
- pkg/replica/backup.go
- pkg/replica/backup_test.go
- pkg/replica/diff_disk.go
- pkg/replica/hash.go
- pkg/replica/replica.go
- pkg/replica/replica_test.go
- pkg/replica/rest/replica.go
- pkg/replica/rest/router.go
- pkg/replica/rpc/dataserver.go
- pkg/replica/server.go
- pkg/sync/rpc/list_test.go
- pkg/sync/rpc/server.go
- pkg/sync/sync.go
- pkg/util/util.go
- pkg/util/validation.go
- scripts/validate
https://github.com/longhorn/longhorn/issues/7448
> fix: golangci-lint error

- Dockerfile.dapper
- integration/common/cli.py
- integration/common/constants.py
- integration/common/frontend.py
- integration/core/conftest.py
- integration/core/test_cli.py
- integration/data/conftest.py
- integration/instance/test_launcher_basic.py
- scripts/integration-test
Issue `None`
Update the dependent instance-manager binary build to address the CVE vulnerabilities.
- The binary is required for launch-simple-file
- This is already addressed on v1.6.x and master branches because they do not use a specific branch.
https://github.com/longhorn/longhorn-engine/blob/v1.6.x/Dockerfile.dapper#L138-L143
`None`
> Fix(v1.5.6): CVE issue from dependent longhorn-instance-manager binary

- pkg/replica/replica.go
Issue Longhorn/longhorn#9168
The deletion of old head disk file is a best-effort task, and the failure should not hinder the following tasks.
The regression is caused by the [commit](https://github.com/longhorn/longhorn-engine/commit/737bf77b6e0f01e68dbb340e4b3421bb0c7417b6#diff-b54af9ffed94a317525bc7609415261b623020d2aa410c124e9fe3b871d2d2bdR918).
> fix(replica): best-effort to delete old head disk file

- pkg/replica/diff_disk.go
- pkg/replica/extents.go
- pkg/replica/replica.go
@ChanYiLin has awesome analysis that sometime we are still loading backing file layer on sle-micro ARM64 when doing backup [link](https://github.com/longhorn/longhorn/issues/9209#issuecomment-2284142447). This is not correct because we should skip loading backing file when doing backup 
The current implementation relies on the assumption that file descriptor of backingFile is always 0 and uses it to skip loading the backingFile layer: [link](https://github.com/longhorn/longhorn-engine/blob/04c645097a4a93e46f0f0391222895ea06b25456/pkg/replica/extents.go#L15-L18) . However, this assumption is not always correct. For example, with RAW backing image, `fd` is not 0. See more details at [link](https://github.com/longhorn/longhorn/issues/9209#issuecomment-2285219668) . For qcow backing image, …
> fix(backup): skip loading the backingFile when doing backup or when user requests exporting the volume without backingFile

- app/cmd/controller.go
- pkg/backend/dynamic/dynamic.go
- pkg/backend/file/file.go
- pkg/backend/remote/remote.go
- pkg/controller/control.go
- pkg/dataconn/client.go
- pkg/types/types.go
- pkg/util/shared_timeouts.go
- pkg/util/util_test.go
longhorn/longhorn#8711
The implementation in this PR makes it possible to configure the engine so that there are two `engineReplicaTimeouts` (short and long). The backends lightly coordinate via a new `SharedTimeouts` struct to ensure that most of them can time out in the normal way after `engineReplicaTimeoutShort`, but exactly one of them must wait `engineReplicaTimeoutLong` to do the same.
~Note that this PR does NOT actually configure a different `engineReplicaTimeoutLong`. My plan is to do that in a followup after this one is approved and we decide exactly how we want to expose the new capability.~
Per https://github.com/longhorn/longhorn-engine/pull/1176#issuecomment-2274190148, I experimented with a different approach in https://github.com/ejweber/longhorn-engine/tree/8711-last-repl …
> feat: support a different timeout for the last replica

- pkg/dataconn/client.go
longhorn/longhorn#8711
Per https://github.com/longhorn/longhorn-engine/pull/1176#discussion_r1728387058, I didn't follow the convention from https://github.com/longhorn/longhorn/wiki/coding-convention#organize-package-imports with a new import.
> refactor(imports): follow convention in dataconn/client.go

- pkg/backend/remote/remote.go
We closed https://github.com/longhorn/longhorn-engine/pull/1199 but still want the fix for the potential orphan goroutine issue in v1.6.x.
> fix(datconn): don't orphan client goroutine when remote is closed (backport #1176)

- pkg/replica/backup.go
ref: https://github.com/longhorn/longhorn/issues/9168
To prevent race conditions where some goroutines might update the status to 'In Progress' after the backup has already completed or failed, we should skip updating the status in such cases.
> fix: skip updating the status if the backup has already completed or failed

- package/Dockerfile
Issue longhorn/longhorn#9132
Fix CVE issues.
**After**
```
c3y1huang/research:2098-lh-ei (suse linux enterprise server 15.5)
=================================================================
Total: 0 (HIGH: 0, CRITICAL: 0)
```
**Before**
```
longhornio/longhorn-engine:v1.6.x-head (suse linux enterprise server 15.5)
==========================================================================
Total: 0 (HIGH: 0, CRITICAL: 0)
usr/local/bin/grpc_health_probe (gobinary)
==========================================
Total: 2 (HIGH: 1, CRITICAL: 1)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬─────────────────┬────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │  Fixed Version  │ …
```
> fix(cve): update dependencies

- package/Dockerfile
Issue longhorn/longhorn#9714
Install the latest grpc_health_probe at build time.
`None`
`None`
> build: install latest grpc_health_probe

- Dockerfile.dapper
> chore(dockerfile): clone and build correct instance-manager codes for v1.7.x

- Dockerfile.dapper
> chore(dockerfile): clone and build correct instance-manager codes

- go.mod
- go.sum
- vendor/modules.txt
Issue longhorn/longhorn#9898
**After**
```
c3y1huang/research:2101-lh-ei (suse linux enterprise server 15.5)
=================================================================
Total: 0 (HIGH: 0, CRITICAL: 0)
usr/local/bin/grpc_health_probe (gobinary)
==========================================
Total: 1 (HIGH: 1, CRITICAL: 0)
┌──────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬───────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                       Title                       │
├──────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼───────────────────────────────────────────────────┤
│ golang.org/x/net │ CVE-2024-45338 …
```
> chore(cve): update vendor

- scripts/build
When `./bin/longhorn-instance-manager` file does exist, `[[ ! -x ./bin/longhorn-instance-manager ]]` evaluates to `false` and return exit code 1. Since `set -e` is enabled, the script immediately exits on this failure.
Always copy and overwrite the `./bin/longhorn-instance-manager` if it exists
> fix: build failed

- .github/workflows/build.yml
- Dockerfile.dapper
Issue #
- pin build runner image to ubuntu:latest
- chattr utility is not found because e2fsprogs package is not existing in the latest ubuntu:22.04 and ubuntu:24.04 runner images
> chore(dockerfile): pin build runner image to ubuntu:latest and install missing e2fsprogs package

- pkg/controller/control.go
- pkg/controller/init_frontend.go
Issue Longhorn/longhorn#8572
To reduce the chance of hitting the read-only issue, the key is to properly tune the timeout setting for the tgt’s timeout_handler. Because the SCSI layer limits the number of outstanding write requests, this ensures that in-flight requests have sufficient time to complete rather than being prematurely terminated.
> feat: increase the timeout of tgt's timeout_handler

- pkg/controller/control.go
- pkg/controller/control_test.go
- pkg/controller/multi_writer_at.go
- pkg/controller/replicator.go
- pkg/replica/diff_disk.go
- pkg/replica/diff_disk_test.go
Issue # longhorn/longhorn#10718
fix the bug that `len(replicaNoSpaceErrMap)` will not be equal to `replicaWritableCount`, for example, the map has two ENOSPC errors for two replicas, and there is only one RW replica left.
> fix: bug when fixing the disk is out of space
